/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-02 14:14:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.model.vo.BoardComment;
import board.model.vo.Board;
import java.util.List;
import member.model.vo.*;

public final class boardView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1576715004000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1575002716000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("board.model.vo.BoardComment");
    _jspx_imports_classes.add("board.model.vo.Board");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	//로그인한 경우
	Member memberLoggedIn
		= (Member)session.getAttribute("memberLoggedIn");
	//System.out.println("memberLoggedIn@index.jsp="+memberLoggedIn);
	
	//쿠키관련
	boolean saveId = false;
	String memberId = "";
	Cookie[] cookies = request.getCookies();
	if(cookies != null){
		//System.out.println("----------------------------");
		for(Cookie c : cookies){
			String k = c.getName();
			String v = c.getValue();
			//System.out.println(k + " = " + v);
			if("saveId".equals(k)){
				saveId = true;
				memberId = v;
			}
			
		}
		
		//System.out.println("----------------------------");
	}
	
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Hello MVC</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\tconsole.log(\"<<jquery loading 완료!!!>>\");\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function loginValidate(){\r\n");
      out.write("\tvar $memberId = $(\"#memberId\");\r\n");
      out.write("\tvar $password = $(\"#password\");\r\n");
      out.write("\t\r\n");
      out.write("\tif($memberId.val().trim().length == 0){\r\n");
      out.write("\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t$memberId.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif($password.val().trim().length == 0){\r\n");
      out.write("\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t$password.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goMemberEnroll(){\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<h1>Hello MVC</h1>\r\n");
      out.write("\t\t\t<!-- 로그인메뉴 -->\r\n");
      out.write("\t\t\t<div class=\"login-container\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t");
if(memberLoggedIn == null){ 
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/member/loginCheck\" \r\n");
      out.write("\t\t\t\t\t  id=\"loginFrm\"\r\n");
      out.write("\t\t\t\t\t  method=\"post\"\r\n");
      out.write("\t\t\t\t\t  onsubmit=\"return loginValidate();\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   name=\"memberId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   id=\"memberId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   placeholder=\"아이디\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   tabindex=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   value=\"");
      out.print(saveId?memberId:"");
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   value=\"로그인\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   tabindex=\"3\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   name=\"password\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   placeholder=\"비밀번호\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   tabindex=\"2\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   name=\"saveId\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   id=\"saveId\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   ");
      out.print(saveId?"checked":"");
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"saveId\">아이디 저장</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   value=\"회원가입\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   onclick=\"goMemberEnroll();\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t");
  }
				else {
			
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<table id=\"logged-in\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(memberLoggedIn.getMemberName() );
      out.write("님, 안녕하세요.</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"내 정보보기\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/memberView?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("'\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"로그아웃\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/logout'\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 로그인메뉴 끝 -->\r\n");
      out.write("\t\t\t<!-- 메인메뉴 시작 -->\r\n");
      out.write("\t\t\t<!-- nav>ul.main-nav>li -->\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<ul class=\"main-nav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"home\"><a href=\"");
      out.print(request.getContextPath());
      out.write("\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"notice\"><a href=\"#\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"board\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/board/boardList\">게시판</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"photo\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/photo/photoList\">사진게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 if(memberLoggedIn != null 
						  && "admin".equals(memberLoggedIn.getMemberId())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"admin\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\">회원관리</a></li>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!-- 메인메뉴 끝 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<section id=\"content\">");
      out.write('\r');
      out.write('\n');

	Board b = (Board)request.getAttribute("board");
	List<BoardComment> commentList 
		= (List<BoardComment>)request.getAttribute("commentList");

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/board.css\" />\r\n");
      out.write("<section id=\"board-container\">\r\n");
      out.write("<h2>게시판</h2>\r\n");
      out.write("<table id=\"tbl-board-view\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>글번호</th>\r\n");
      out.write("\t\t<td>");
      out.print(b.getBoardNo() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>제 목</th>\r\n");
      out.write("\t\t<td>");
      out.print(b.getBoardTitle() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>작성자</th>\r\n");
      out.write("\t\t<td>");
      out.print(b.getBoardWriter() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>조회수</th>\r\n");
      out.write("\t\t<td>");
      out.print(b.getReadCount() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>첨부파일</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t");
 if(b.getOriginalFileName() != null){ 
      out.write("\r\n");
      out.write("\t\t\t<a href=\"javascript:fileDownload('");
      out.print(b.getOriginalFileName());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(b.getRenamedFileName());
      out.write("');\">\r\n");
      out.write("\t\t\t\t<img alt=\"첨부파일\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/file.png\" width=16px>");
      out.print( b.getOriginalFileName() );
      out.write("\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t");
 }
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>내 용</th>\r\n");
      out.write("\t\t<td>");
      out.print(b.getBoardContent());
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
 if(memberLoggedIn!=null && 
		(b.getBoardWriter().equals(memberLoggedIn.getMemberId())
		|| "admin".equals(memberLoggedIn.getMemberId())) ){ 
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th colspan=\"2\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"수정하기\" onclick=\"updateBoard()\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"삭제하기\" onclick=\"deleteBoard()\">\r\n");
      out.write("\t\t</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<form name=\"boardDelFrm\" action=\"");
      out.print(request.getContextPath());
      out.write("/board/boardDelete\" method=\"post\">\r\n");
      out.write("\t    <input type=\"hidden\" name=\"boardNo\" value=\"");
      out.print(b.getBoardNo() );
      out.write("\" />\r\n");
      out.write("\t    <input type=\"hidden\" name=\"renamedFileName\" value=\"");
      out.print(b.getRenamedFileName()!=null?b.getRenamedFileName():"" );
      out.write("\" />\r\n");
      out.write("    </form>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction updateBoard(){\r\n");
      out.write("\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/board/boardUpdateForm?boardNo=");
      out.print(b.getBoardNo());
      out.write("\";\t\r\n");
      out.write("\t}\r\n");
      out.write("   \tfunction deleteBoard(){\r\n");
      out.write("        if(!confirm('이 게시글을 정말 삭제하시겠습니까?')) return;\r\n");
      out.write("        $(\"[name=boardDelFrm]\").submit();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t");
} 
      out.write("\t\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<hr style=\"margin-top:30px;\"/>\r\n");
      out.write("\r\n");
      out.write("<div class=\"comment-container\">\r\n");
      out.write("\t<div class=\"comment-editor\">\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/board/boardCommentInsert\"\r\n");
      out.write("\t\t\t  method=\"post\"\r\n");
      out.write("\t\t\t  name=\"boardCommentFrm\">\r\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"boardRef\" \r\n");
      out.write("\t\t\t  \t\t value=\"");
      out.print(b.getBoardNo() );
      out.write("\" />\r\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"boardCommentWriter\"\r\n");
      out.write("\t\t\t  \t\t value=\"");
      out.print(memberLoggedIn!=null?memberLoggedIn.getMemberId():"" );
      out.write("\" />\r\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"boardCommentLevel\" value=\"1\" />\r\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"boardCommentRef\" value=\"0\" />\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  <textarea name=\"boardCommentContent\" cols=\"60\" rows=\"3\"></textarea>\r\n");
      out.write("\t\t\t  <input type=\"submit\" id=\"btn-insert\" value=\"등록\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 댓글목록테이블 -->\r\n");
      out.write("\t<table id=\"tbl-comment\">\r\n");
      out.write("\t");

		if(commentList != null && !commentList.isEmpty()){
			for(BoardComment bc : commentList){
				//1.댓글인 경우
				if(bc.getBoardCommentLevel() == 1){
	
      out.write("\r\n");
      out.write("\t\t<tr class=\"level1\">\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<sub class=\"comment-writer\">");
      out.print(bc.getBoardCommentWriter() );
      out.write("</sub>\r\n");
      out.write("\t\t\t\t<sub class=\"comment-date\">");
      out.print(bc.getBoardCommentDate() );
      out.write("</sub>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t");
      out.print(bc.getBoardCommentContent() );
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<button class=\"btn-reply\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(bc.getBoardCommentNo());
      out.write("\">답글</button>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- @실습문제: 글쓴 본인 혹은 관리자에게만 노출시킬것 -->\r\n");
      out.write("\t\t\t\t<!-- /board/boardCommentDelete -->\r\n");
      out.write("\t\t\t\t<!-- 삭제후, 삭제성공 메세지를 보여준후 현재페이지로 돌아올것. -->\t\t\r\n");
      out.write("\t\t\t\t");
if(memberLoggedIn!=null 
					&& ("admin".equals(memberLoggedIn.getMemberId()) 
							|| bc.getBoardCommentWriter().equals(memberLoggedIn.getMemberId()) )){
      out.write("\r\n");
      out.write("\t\t\t\t<button class=\"btn-delete\" value=\"");
      out.print(bc.getBoardCommentNo());
      out.write("\">삭제</button>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t");

				}
				//2.대댓글(답글)인 경우
				else{
	
      out.write("\r\n");
      out.write("\t\t<tr class=\"level2\">\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<sub class=\"comment-writer\">");
      out.print(bc.getBoardCommentWriter() );
      out.write("</sub>\r\n");
      out.write("\t\t\t\t<sub class=\"comment-date\">");
      out.print(bc.getBoardCommentDate() );
      out.write("</sub>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t");
      out.print(bc.getBoardCommentContent() );
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t");
if(memberLoggedIn!=null 
					&& ("admin".equals(memberLoggedIn.getMemberId()) 
							|| bc.getBoardCommentWriter().equals(memberLoggedIn.getMemberId()) )){
      out.write("\r\n");
      out.write("\t\t\t\t<button class=\"btn-delete\" value=\"");
      out.print(bc.getBoardCommentNo());
      out.write("\">삭제</button>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t");

				}
			}
		}
	
      out.write("\r\n");
      out.write("\t</table> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("    //삭제버튼 클릭시\r\n");
      out.write("    $(\".btn-delete\").click(function(){\r\n");
      out.write("        if(!confirm(\"정말 삭제하시겠습니까?\")) return;\r\n");
      out.write("        //삭제처리후 돌아올 현재게시판번호도 함께 전송함.\r\n");
      out.write("        location.href=\"");
      out.print(request.getContextPath());
      out.write("/board/boardCommentDelete?boardNo=");
      out.print(b.getBoardNo() );
      out.write("&del=\"+$(this).val();\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//대댓글(답글)버튼 .btn-reply\r\n");
      out.write("\t$(\".btn-reply\").on(\"click\", function(e){\r\n");
      out.write("\t\t");
 	if(memberLoggedIn == null){
      out.write("\r\n");
      out.write("\t\t\t\tloginAlert();\r\n");
      out.write("\t\t");
 	}
			//로그인한 경우
			else {
		
      out.write("\r\n");
      out.write("\t\t\tvar tr = $(\"<tr></tr>\");\r\n");
      out.write("\t\t\tvar html = '<td style=\"display:none; text-align:left;\" colspan=2>';\r\n");
      out.write("\t\t\thtml += '<form action=\"");
      out.print(request.getContextPath());
      out.write("/board/boardCommentInsert\" method=\"POST\">';\r\n");
      out.write("\t\t\thtml += '<input type=\"hidden\" name=\"boardRef\" value=\"");
      out.print(b.getBoardNo());
      out.write("\" />';\r\n");
      out.write("\t\t\thtml += '<input type=\"hidden\" name=\"boardCommentWriter\" value=\"");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" />';\r\n");
      out.write("\t\t\thtml += '<input type=\"hidden\" name=\"boardCommentLevel\" value=\"2\" />';\r\n");
      out.write("\t\t\thtml += '<input type=\"hidden\" name=\"boardCommentRef\" value=\"'+$(this).val()+'\" />';\r\n");
      out.write("\t\t\thtml += '<textarea name=\"boardCommentContent\" cols=\"60\" rows=\"1\"></textarea>';\r\n");
      out.write("\t\t\thtml += '<input type=\"submit\" class=\"btn-insert2\" value=\"등록\" />';\r\n");
      out.write("\t\t\thtml += '</form></td>';\r\n");
      out.write("\t\t\ttr.html(html);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconsole.log($(this).parent().parent());//tr.level1\r\n");
      out.write("\t\t\tconsole.log(tr.children('td'));//방금 생성한 td\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttr.insertAfter($(this).parent().parent())\r\n");
      out.write("\t\t\t  .children('td')\r\n");
      out.write("\t\t\t  .slideDown(800)\r\n");
      out.write("\t\t\t  .children('form')\r\n");
      out.write("\t\t\t  .submit(function(e){\r\n");
      out.write("\t\t\t\t var $textarea = $(this).children(\"textarea\");\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t if($textarea.val().trim().length == 0)\r\n");
      out.write("\t\t\t\t\t e.preventDefault();\r\n");
      out.write("\t\t\t\t \t\r\n");
      out.write("\t\t\t  });\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

			}		
		
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t//textarea\r\n");
      out.write("\t$(\"[name=boardCommentContent]\").click(function(){\r\n");
      out.write("\t\tif(");
      out.print(memberLoggedIn == null);
      out.write("){\r\n");
      out.write("\t\t\tloginAlert();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//submit: jquery방식 - preventDefault함수 사용 \r\n");
      out.write("\t$(\"[name=boardCommentFrm]\").submit(function(e){\r\n");
      out.write("\t\tif(");
      out.print(memberLoggedIn == null);
      out.write("){\r\n");
      out.write("\t\t\tloginAlert();\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar $content = $(\"[name=boardCommentContent]\");\r\n");
      out.write("\t\tif($content.val().trim().length == 0){\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function loginAlert(){\r\n");
      out.write("\talert(\"로그인 후 이용할 수 있습니다.\");\r\n");
      out.write("\t$(\"#memberId\").focus();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function fileDownload(oName, rName){\r\n");
      out.write("\t//ie대비 한글인코딩 명시적 처리\r\n");
      out.write("\toName = encodeURIComponent(oName);\r\n");
      out.write("\tconsole.log(oName);\r\n");
      out.write("\t\r\n");
      out.write("\tlocation.href \r\n");
      out.write("\t\t= \"");
      out.print(request.getContextPath());
      out.write("/board/fileDownload?oName=\"+oName+\"&rName=\"+rName;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<p>&lt;Copyright 2017. <strong>KH정보교육원</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
