/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-29 17:18:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.faq;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.*;

public final class faqBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1577639837852L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1577465951749L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
 
	//로그인한 경우
	Member memberLoggedIn= (Member)session.getAttribute("memberLoggedIn");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>re:flex</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Libre+Barcode+128+Text|Monoton|Permanent+Marker|Righteous|Seymour+One|Stalinist+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\"> <!-- 부트스트랩 -->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/mypage.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/header.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"container-fluid navbar-fixed-top\">\r\n");
      out.write("        <div id=\"header-wrapper\" class=\"row\">\r\n");
      out.write("            <div id=\"logo\" class=\"col-md-4\">\r\n");
      out.write("                <h1 class=\"eng\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">re:flex</a></h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"search\" class=\"col-md-4\">\r\n");
      out.write("                <h2 class=\"sr-only\">상품 검색</h2>\r\n");
      out.write("                <form action=\"\">\r\n");
      out.write("                    <button type=\"submit\" id=\"btn-search\" aria-label=\"search products\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <input type=\"search\" name=\"search\" placeholder=\"검색\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"menu\" class=\"col-md-4\">\r\n");
      out.write("                <ul class=\"list-unstyled list-inline text-right\">\r\n");
      out.write("                    ");
if(memberLoggedIn==null){ 
      out.write("\r\n");
      out.write("\t                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\r\n");
      out.write("\t                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\r\n");
      out.write("                    ");

                    	}
                    	else{
                    
      out.write("\r\n");
      out.write("\t                    <li><span class=\"strong\">");
      out.print(memberLoggedIn.getMemberName());
      out.write("</span>님</li>                    \r\n");
      out.write("\t                    <li>\r\n");
      out.write("\t                    \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">로그아웃</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("             \r\n");
      out.write("\t                    </li>\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <h2 class=\"sr-only\">장바구니</h2>\r\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberCart\" aria-label=\"cart\"><span class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <button type=\"button\"  id=\"btn-sidemenu\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-list\" aria-hidden=\"true\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- side menu -->\r\n");
      out.write("                <!-- level1 -->\r\n");
      out.write("                <div id=\"sidemenu-closeLayer\">\r\n");
      out.write("                <nav id=\"level1-sidemenu\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header></header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li id=\"recommended\" data-target=\"#level2-recommended\"><a href=\"#\">이럴 때 빌려봐<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("                        ");
 if(memberLoggedIn != null  && "admin".equals(memberLoggedIn.getMemberId())){ 
      out.write("\r\n");
      out.write("                        \t<li id=\"adminPage\" data-target=\"#level2-adminPage\"><a href=\"#\">관리자페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 }
                        	else{ 
                        
      out.write("\r\n");
      out.write("                        \t<li id=\"mypage\" data-target=\"#level2-mypage\"><a href=\"#\">마이페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/faq/faqBoard\">고객서비스(FAQ)</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/faq/faqIndex\">re:flex 소개</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- level2: 이럴때빌려봐 -->\r\n");
      out.write("                <nav id=\"level2-recommended\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                        \t<span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                              이럴 때 빌려봐\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT01\">반려동물과 함께 할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT02\">육아할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT03\">파티할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT04\">운동할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT05\">여행갈 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT06\">캠핑갈 때</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- level2: 마이페이지 / 로그인 안했으면 경고창 -->\r\n");
      out.write("                \r\n");
      out.write("                <nav id=\"level2-mypage\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                            마이페이지\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    \r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOrderList\">주문조회</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlist\">위시리스트</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalIng\">계약중인 렌탈</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalFin\">종료중인 렌탈</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypagePoint\">포인트 확인</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageReview\">이용후기 내역</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOneToOne\">1:1문의 내역</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberUpdate\">회원정보 수정</a></li>\r\n");
      out.write("                        <li><a href=\"\">회원정보 탈퇴</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <nav id=\"level2-adminPage\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                    \r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                            관리자페이지\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"#\">상품관리</a></li>\r\n");
      out.write("                        <li><a href=\"#\">주문관리</a></li>\r\n");
      out.write("                        <li><a href=\"#\">회원관리</a></li>\r\n");
      out.write("                 \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(()=>{\r\n");
      out.write("        $(\".faq_content\").hide();\r\n");
      out.write("        $(\".faq\").on(\"click\", function(){\r\n");
      out.write("\r\n");
      out.write("            $(this).next().slideToggle();\r\n");
      out.write("\r\n");
      out.write("            console.log(\"이벤트핸들러 안 : \", this); //클릭한 div\r\n");
      out.write("            var $div = $(this);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function showContent(sectionId){\r\n");
      out.write("    let sectionArr = document.querySelectorAll(\".faq-container\");\r\n");
      out.write("    console.log(sectionArr);\r\n");
      out.write("    for(let i in sectionArr){\r\n");
      out.write("    let section = sectionArr[i];\r\n");
      out.write("    if(section.id===sectionId){\r\n");
      out.write("        $(sectionArr).removeClass('is-selected');\r\n");
      out.write("        $(section).addClass('is-selected');\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid line-style text-center contents none-nav faqboard\">\r\n");
      out.write("        <p>자주 묻는 질문</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-1\"></div>\r\n");
      out.write("                <div class=\"col-md-10 content-wrapper\">\r\n");
      out.write("                        <div id=\"wrapper\" class=\"row\">\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <p id=\"category\">카테고리 선택</p>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <ul class=\"list-inline list-unstyled text-center\">\r\n");
      out.write("                                    <li data-tab-ref=\"shopping\" class=\"is-selected\"><button type=\"button\" onclick=\"showContent('shopping');\">쇼핑</button></li>\r\n");
      out.write("                                    <li data-tab-ref=\"payment\"><button type=\"button\" onclick=\"showContent('payment');\">결제</button></li>\r\n");
      out.write("                                    <li data-tab-ref=\"delivery\"><button type=\"button\" onclick=\"showContent('delivery');\">배송</button></li>\r\n");
      out.write("                                    <li data-tab-ref=\"my-account\"><button type=\"button\" onclick=\"showContent('my-account');\">나의 계정</button></li>\r\n");
      out.write("                                    <li data-tab-ref=\"sustainability\"><button type=\"button\" onclick=\"showContent('sustainability');\">환경</button></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            \r\n");
      out.write("\r\n");
      out.write("                                    <!-- 쇼핑 -->\r\n");
      out.write("                                    <div class=\"faq-container is-selected\" id=\"shopping\">\r\n");
      out.write("                                    <div class=\"shopping\">\r\n");
      out.write("                                        <p class=\"text-center\">쇼핑</p>                     \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"faq\">&nbsp;&nbsp;REFLEX.COM에서 주문\r\n");
      out.write("                                        <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- 1 -->\r\n");
      out.write("                                    <p class=\"faq_content\">\r\n");
      out.write("                                        Balenciaga.com에서 제품을 구매하시려면 가입해주시기 바랍니다. 회원으로 가입하시면, 발렌시아가 고객만을 위한 특별한 페이지 및 서비스를 이용하실 수 있습니다.\r\n");
      out.write("                                        <br> \r\n");
      out.write("                                        제품 검색\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        보다 간편하게 카탈로그를 살펴보시려면, 탐색 메뉴에서 카테고리를 선택하세요. 특정 제품을 찾고 싶으실 경우, 필터나 웹사이트 내부 검색을 이용하세요.\r\n");
      out.write("                                        <br> \r\n");
      out.write("                                        <br>\r\n");
      out.write("                                            제품 정보\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                            각 제품 페이지에서 구매 가능한 모든 사이즈 및 컬러, 제품 설명 및 구성을 확인하실 수 있습니다. 제품 이미지를 클릭하여 확대해 모든 디테일을 확인하세요.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                            주문 방법:\r\n");
      out.write("                                        <br>  \r\n");
      out.write("                                            – 제품 페이지에서 원하는 컬러와 사이즈를 선택하세요. <br>\r\n");
      out.write("                                            – 제품을 장바구니에 추가하세요. <br>\r\n");
      out.write("                                            – 쇼핑을 마치면 장바구니를 클릭하세요. <br>\r\n");
      out.write("                                            – 배송 방법과 결제 방법을 선택하세요. <br>\r\n");
      out.write("                                            – 배송 정보를 입력하고 다음 페이지에서 결제 정보를 입력합니다. <br>\r\n");
      out.write("                                            – 정보가 정확하게 입력되었는지 확인하고 “구매하기”를 클릭합니다. <br>\r\n");
      out.write("                                        <br>    \r\n");
      out.write("                                        <br>\r\n");
      out.write("                                            몇 분 후, 주문 내역을 확인할 수 있는 이메일이 발송됩니다. 이후 물류센터가 모든 배송 과정을 담당하며, 주문 제품이 배송된 직후 다시 한번 확인 이메일이 발송됩니다.\r\n");
      out.write("                                        Reflex.com에서 제품을 구매하시려면 가입해주시기 바랍니다. 회원으로 가입하시면, 발렌시아가 고객만을 위한 특별한 페이지 및 서비스를 이용하실 수 있습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                            제품 검색\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                            보다 간편하게 카탈로그를 살펴보시려면, 탐색 메뉴에서 카테고리를 선택하세요. 특정 제품을 찾고 싶으실 경우, 필터나 웹사이트 내부 검색을 이용하세요.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        <br>  \r\n");
      out.write("                                            제품 정보\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                            각 제품 페이지에서 구매 가능한 모든 사이즈 및 컬러, 제품 설명 및 구성을 확인하실 수 있습니다. 제품 이미지를 클릭하여 확대해 모든 디테일을 확인하세요.\r\n");
      out.write("                                        <br>    \r\n");
      out.write("                                        <br>    \r\n");
      out.write("                                            주문 방법:\r\n");
      out.write("                                        <br>    \r\n");
      out.write("                                            – 제품 페이지에서 원하는 컬러와 사이즈를 선택하세요. <br>\r\n");
      out.write("                                            – 제품을 장바구니에 추가하세요. <br>\r\n");
      out.write("                                            – 쇼핑을 마치면 장바구니를 클릭하세요. <br>\r\n");
      out.write("                                            – 배송 방법과 결제 방법을 선택하세요. <br>\r\n");
      out.write("                                            – 배송 정보를 입력하고 다음 페이지에서 결제 정보를 입력합니다. <br>\r\n");
      out.write("                                            – 정보가 정확하게 입력되었는지 확인하고 “구매하기”를 클릭합니다. <br>\r\n");
      out.write("                                        <br>    \r\n");
      out.write("                                        <br>    \r\n");
      out.write("                                            몇 분 후, 주문 내역을 확인할 수 있는 이메일이 발송됩니다. 이후 물류센터가 모든 배송 과정을 담당하며, 주문 제품이 배송된 직후 다시 한번 확인 이메일이 발송됩니다. <br></p>\r\n");
      out.write("                                    <!-- 2 -->\r\n");
      out.write("                                    <div class=\"faq\">&nbsp;&nbsp;주문 완료 후 24시간 이상 지났는데 아직까지 주문 확인 메일을 받지 못했습니다. 어떻게 해야 하나요?\r\n");
      out.write("                                            <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"faq_content\">스팸 폴더를 확인하여 이메일 계정에서 <br>\r\n");
      out.write("                                            confirmation@store.reflex.com 및 shipping@store.reflex.com의 이메일 주소를 안전한 발송자로 분류하여 해당 주소에서 발송한 메일을 안전하게 받을 수 있도록 하십시오. <br>\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            이렇게 함으로써, 안티 스팸 필터에 의해 이메일 커뮤니케이션이 차단되지 않습니다. 여전히 문제가 발생할 경우, 등록한 이메일 주소에 오류가 있을 수 있으므로 리플렉스로 연락해주시기 바랍니다. <br></p>\r\n");
      out.write("                                    <!-- 3 -->\r\n");
      out.write("                                    <div class=\"faq\">&nbsp;&nbsp;주문을 변경하고 다른 상품을 추가하거나 삭제할 수 있나요?\r\n");
      out.write("                                            <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"faq_content\">죄송합니다만 불가능합니다. 각각의 주문은 자동적으로 진행이 되어 일단 주문이 확정되면 세부 내용은 수정이 불가능합니다. 추가로 아이템을 구매하기 원하시면 새로운 주문을 진행하셔야 합니다. 반품을 원하실 경우, 저희 반품정책을 참조해 주세요. <br></p>\r\n");
      out.write("                                    <!-- 4 -->\r\n");
      out.write("                                    <div class=\"faq\">&nbsp;&nbsp;프리 오더는 무엇이며 어떻게 진행되나요?\r\n");
      out.write("                                            <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"faq_content\">‘사전 주문’은 아직 판매를 시작하지 않았지만, 곧 판매 예정인 제품을 예약하는 방법입니다. 예상 배송일은 각 사전 주문 아이템의 제품 페이지 내에 명시되어 있습니다. 예상 배송일은 사정에 따라 변경될 수 있습니다. 이 경우, 이메일로 새로운 배송일을 알려드립니다. <br>\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            – 현재 구매 가능한 제품과 사전 주문 아이템을 포함한 주문: 제품은 두 번에 걸쳐 배송되지만, 배송비는 한 번만 청구됩니다. <br>\r\n");
      out.write("                                            – 서로 다른 배송일이 예상되는 사전 주문 아이템을 포함한 주문: 최신 예상 배송일에 제품이 함께 배송됩니다. <br>\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            모든 경우, 상품이 배송되자마자 확인 이메일이 발송됩니다. <br>\r\n");
      out.write("                                            사전 주문 제품은 신용카드로만 구매하실 수 있습니다. 주문을 완료하면, 고객의 은행에 제공된 정보를 확인합니다. 신용카드 유효성은 호주 주문의 경우 2호주 달러, 홍콩 주문의 경우 10홍콩 달러, 다른 모든 국가는 1유로의 지불 인증으로 확인할 수 있으며, 인증은 별도로 비용이 청구되지 않습니다. Balenciaga.com은 상품이 배송되는시점에만 카드 비용을 청구합니다. <br></p>\r\n");
      out.write("                                    <!-- 5 -->\r\n");
      out.write("                                    <div class=\"faq\">&nbsp;&nbsp;기프트 옵션\r\n");
      out.write("                                            <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"faq_content\">리플렉스의 모든 제품은 로고 박스에 담겨 발송됩니다. 기프트 옵션을 선택하시면 기프트 영수증이 발송되며, 기프트 메시지를 남기실 수 있습니다호주 주문의 경우 2호주 달러, 홍콩 주문의 경우 10홍콩 달러, 다른 모든 국가는 1유로의 지불 인증으로 확인할 수 있으며, 인증은 별도로 비용이 청구되지 않습니다. Reflex.com은 상품이 배송되는시점에만 카드 비용을 청구합니다. <br></p>\r\n");
      out.write("                                    <!-- 6 -->\r\n");
      out.write("                                    <div class=\"faq\">&nbsp;&nbsp;쇼핑백에 추가한 아이템이 사라진 이유가 무엇인가요?\r\n");
      out.write("                                            <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"faq_content\">쇼핑백에 담아둔 아이템일지라도 결제를 완료하기 이전에는 웹사이트에 구매 가능한 상태로 남아 있기 때문에 다른 고객님께서 먼저 구매할 수 있으므로 재고가 소진될 수도 있습니다. 만약 이러한 경우가 발생하면, 고객님께서 선택한 아이템의 재고가 소진되었음을 알려드립니다. <br></p>\r\n");
      out.write("                                    <!-- 7 -->\r\n");
      out.write("                                    <div class=\"faq\">&nbsp;&nbsp;주문을 취소할 수 있나요?\r\n");
      out.write("                                            <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"faq_content\">죄송합니다. 주문이 확정된 이후에는 모든 과정이 자동으로 처리되어 취소가 불가합니다. <br>\r\n");
      out.write("                                            온라인 반품 정책에 따라 상품을 반품하실 수 있습니다. <br></p>\r\n");
      out.write("                                    <!-- 8 -->\r\n");
      out.write("                                    <div class=\"faq\">&nbsp;&nbsp;주문현황\r\n");
      out.write("                                            <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"faq_content\">주문 준비 단계: 주문이 확정되고 주문 번호와 함께 확인 이메일을 이미 발송한 상태입니다. <br>\r\n");
      out.write("                                            주문 배송: 창고에서 주문 제품이 배송된 직후 배송을 추적할 수 있는 추적 번호와 함께 확인 이메일을 발송합니다. <br>\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            주문 확인 페이지에 주문 번호를 입력하여 언제든지 주문 상태를 확인할 수 있습니다. 회원가입을 완료한 경우 ‘나의 계정’에서 주문과 관련된 모든 정보를 확인할 수 있습니다. <br></p>\r\n");
      out.write("\r\n");
      out.write("                        </div> \r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- 결제 -->\r\n");
      out.write("                            <div class=\"faq-container\" id=\"payment\">\r\n");
      out.write("                            <div class=\"payment\">\r\n");
      out.write("                                <p class=\"text-center\">결제</p>                     \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"faq\">&nbsp;&nbsp;한 건의 주문에 중복 청구가 되었는데 어떻게 해야 하나요?\r\n");
      out.write("                                    <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- 1 -->\r\n");
      out.write("                                <p class=\"faq_content\">\r\n");
      out.write("                                        Reflex에서는 고객님의 신용카드로 결제하신 금액을 한 번만 청구합니다. 명세서에 두 번 청구된 것으로 보일 수 있지만 이 경우, 첫 번째는 주문 시 발생한 결제 승인 요청에 해당하는 것이고, 두 번째가 실제 청구 금액입니다. <br></p>\r\n");
      out.write("                                <!-- 2 -->\r\n");
      out.write("                                <div class=\"faq\">&nbsp;&nbsp;결제 보안\r\n");
      out.write("                                        <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"faq_content\">Reflex은(는) Trustwave 및 Geotrust 인증 보안 서버를 이용하고 최첨단 암호화 서비스(SSL)를 구현하여 모든 구매에 대해 최고 수준의 보안을 보장합니다. 결제 시스템은 브라우저 주소 표시줄의 “https” 웹 주소와 잠금 기호로 표시되는 안전한 연결 방법만을 채택하여 사용합니다. <br>\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        안전한 신용카드 구매를 위해 결제 시 CVV 코드를 반드시 입력해야 합니다. 저희 결제 담당 부서에서 거래를 승인하기 전에 사기행각을 방지하기 위한 검사를 수행할 수 있으며, 보안을 더욱 강화하기 위해 주문을 확인하기 전 고객님께 세부 정보를 문의할 수도 있습니다. <br></p>\r\n");
      out.write("                                <!-- 3 -->\r\n");
      out.write("                                <div class=\"faq\">&nbsp;&nbsp;결제가 되지 않는 이유는 무엇인가요?\r\n");
      out.write("                                        <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"faq_content\">선택하신 결제 방법에 대한 세부 정보를 정확하게 입력했는지 확인하세요. <br>\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        신용카드 결제 시 계속해서 문제가 발생하는 경우 신용카드 회사에 문의하시기 바랍니다. <br>\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        문의사항이 있거나 도움이 필요하시면 연락주시기 바랍니다. <br></p>\r\n");
      out.write("                                <!-- 4 -->\r\n");
      out.write("                                <div class=\"faq\">&nbsp;&nbsp;신용카드로 결제하면 언제 청구되나요?\r\n");
      out.write("                                        <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"faq_content\">주문을 완료하면 신용카드의 유효성과 사용 한도 금액을 확인하기 위해 필요한 결제 승인이 자동으로 요청됩니다. 금액은 이때 결제되는 것이 아니라, 주문 발송 시 결제되고 동시에 고객님께 이메일로 알려드립니다. <br></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- 배송 -->\r\n");
      out.write("                            <div class=\"faq-container\" id=\"delivery\">\r\n");
      out.write("                            <div class=\"delivery\">\r\n");
      out.write("                                <p class=\"text-center\">배송</p>                     \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"faq\">&nbsp;&nbsp;어디에서 주문 진행 상황을 알 수 있나요?\r\n");
      out.write("                                    <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- 1 -->\r\n");
      out.write("                                <p class=\"faq_content\">\r\n");
      out.write("                                    Reflex에서는 고객님의 신용카드로 결제하신 금액을 한 번만 청구합니다. 명세서에 두 번 청구된 것으로 보일 수 있지만 이 경우, 첫 번째는 주문 시 발생한 결제 승인 요청에 해당하는 것이고, 두 번째가 실제 청구 금액입니다. <br></p>\r\n");
      out.write("                                <!-- 2 -->\r\n");
      out.write("                                <div class=\"faq\">&nbsp;&nbsp;주문한 제품이 아직 배송되지 않았는데 어떻게 해야 하나요?\r\n");
      out.write("                                        <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"faq_content\">주문한 제품이 아직 배송되지 않았는데 어떻게 해야 하나요? <br>\r\n");
      out.write("                                    주문한 제품이 예상 기간 내에 배송되지 않은 경우 다음 사항을 참고하시기 바랍니다. <br>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    – 주문 현황을 확인하세요. 가입하신 고객님께서는 주문 섹션에서 확인하실 수 있으며, 또한 주문 확인 이메일에 기재된 주문 번호를 나의 주문정보 페이지에 입력하여 확인하실 수 있습니다. <br>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    – 지정된 배송지의 주소가 정확한지 확인하세요. <br>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    – 배송을 놓쳐 받지 못한 경우 (으)로 UPS에 문의하세요. <br>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    문의사항이 있거나 도움이 필요하시면 연락주시기 바랍니다. <br></p>\r\n");
      out.write("                                <!-- 3 -->\r\n");
      out.write("                                <div class=\"faq\">&nbsp;&nbsp;배송 제한\r\n");
      out.write("                                        <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"faq_content\">유치 우편, 우편 사서함, 우체국 임치제에 대한 배송은 지원하지 않습니다. 이러한 주소로 주문할 경우, 주문은 자동으로 취소됩니다. <br>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    주문의 배송 주소는 반드시 주문이 이루어진 지역과 일치해야 합니다. 배송 주소와 다른 지역에서 이루어진 주문은 자동으로 취소됩니다. 주문하시려면 모든 페이지의 끝부분에 있는 링크에서 해당하는 지역을 바르게 선택해 주세요. <br></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- 나의 계정  -->\r\n");
      out.write("                            <div class=\"faq-container\" id=\"my-account\">\r\n");
      out.write("                            <div class=\"my-account\">\r\n");
      out.write("                                    <p class=\"text-center\">나의 계정</p>                     \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"faq\">&nbsp;&nbsp;나의 계정에 로그인이 안됩니다. 어떻게 해야 하나요?\r\n");
      out.write("                                    <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- 1 -->\r\n");
      out.write("                                <p class=\"faq_content\">\r\n");
      out.write("                                    비밀번호를 잊으신 경우 로그인 페이지의 “비밀번호를 잊으셨나요?” 링크를 클릭하여 비밀번호 변경 절차를 진행하시기 바랍니다. <br>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    문의사항이 있거나 도움이 필요하시면 연락주시기 바랍니다. <br></p>\r\n");
      out.write("                                <!-- 2 -->\r\n");
      out.write("                                <div class=\"faq\">&nbsp;&nbsp;계정은 어떻게 삭제하나요?\r\n");
      out.write("                                        <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"faq_content\">나의 계정의 삭제를 원하시면 저희에게 연락주시기 바랍니다. <br></p>\r\n");
      out.write("                            \r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- 환경 -->\r\n");
      out.write("                            <div class=\"faq-container\" id=\"sustainability\">\r\n");
      out.write("                            <div class=\"sustainability\">\r\n");
      out.write("                                <p class=\"text-center\">환경</p>                     \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"faq\">&nbsp;&nbsp;지속 가능한 미래를 위하여\r\n");
      out.write("                                    <span class=\"glyphicon glyphicon-menu-down menudown\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- 1 -->\r\n");
      out.write("                                <p class=\"faq_content\">\r\n");
      out.write("                                    지속가능성에 대한 신념을 바탕으로 우수한 품질의 제품을 제공하고 사업을 운영하고 있는 리플렉스는 좀 더 나은 세상과 지속 가능한 미래를 위한 브랜드의 노력을 반영하는 컬렉션을 창조합니다. <br>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    리플렉스는 지속가능성에 대한 의무감을 가지고, 의식 있는 럭셔리 패션을 추구하는 고객에게 완벽하게 호응할 수 있도록 지속적인 노력을 기울이고 있습니다. <br>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    브랜드의 모회사 케어링과 동일한 비전을 가지고 리플렉스는 다음의 5개 주요 사항을 실천하고 있습니다. <br>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    – 그룹 활동을 통한 전 직원의 지속가능성 지원 기획의 참여 도모 <br>\r\n");
      out.write("                                    – 사업 활동과 제품 생산 및 공급 체계에 있어 환경 오염의 최소화 (온실 가스, 수자원, 폐기물) <br>\r\n");
      out.write("                                    – 환경에 어떠한 악영향도 미치지 않는 제품의 제공 <br>\r\n");
      out.write("                                    – 관련 납품회사의 지속가능성 기획을 지원하여 사회 및 환경에 공헌하도록 유도 <br>\r\n");
      out.write("                                    – 천연자원 보호 – 리플렉스의 창조력과 혁신의 원천을 이루는 자연을 위해 생물 다양성 보존과 자연 및 동물 보호 <br>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    저희 브랜드의 지속가능성 지원기획에 대한 자세한 정보는 sustainability@kr.reflex.com으로 문의해주시기 바랍니다. <br></p>\r\n");
      out.write("                                \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-1\"></div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <style>\r\n");
      out.write("            .faqboard{border-top:0;}\r\n");
      out.write("            #category{text-align:center;}\r\n");
      out.write("            #wrapper li{text-align:center; margin-left:10px; margin-bottom: 10px;}\r\n");
      out.write("            .faq{height:50px; line-height:50px; border-top:1px solid;}\r\n");
      out.write("            .faq-container{display:none;}\r\n");
      out.write("            .faq-container.is-selected{display: block;}\r\n");
      out.write("            .shopping{height:50px; line-height:50px; border-top:1px solid;}\r\n");
      out.write("            .payment{height:50px; line-height:50px; border-top:1px solid;}\r\n");
      out.write("            .delivery{height:50px; line-height:50px; border-top:1px solid;}\r\n");
      out.write("            .my-account{height:50px; line-height:50px; border-top:1px solid;}\r\n");
      out.write("            .sustainability{height:50px; line-height:50px; border-top:1px solid;}\r\n");
      out.write("            .menudown{float:right; padding-top:15px; margin-right: 20px;};\r\n");
      out.write("\r\n");
      out.write("            </style>\r\n");
      out.write("\r\n");
      out.write("    <!-- 맨위로 이동 버튼 -->\r\n");
      out.write("    <div id=\"go-to-top\" class=\"btn-bottom\">\r\n");
      out.write("        <button type=\"button\" id=\"btn-gotop\" class=\"center-block\">맨 위로 이동</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"container-fluid\">\r\n");
      out.write("\t    <div class=\"line-style\"></div>\r\n");
      out.write("\t    <!-- first line -->\r\n");
      out.write("\t    <div id=\"footer-menu\" class=\"row\">\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>회사소개</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">정책안내</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>고객서비스</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">1:1문의</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">주문현황</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>문의하기</header>\r\n");
      out.write("\t            <p id=\"q-call\" class=\"lead\">1577-1577</p>\r\n");
      out.write("\t            <p id=\"q-email\" class=\"lead\">reflex@naver.com</p>\r\n");
      out.write("\t            <p>평일 10:00~18:00</p>\r\n");
      out.write("\t            <p>주말 및 공휴일 휴무</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>SNS</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">Facebook</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">Instagram</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">Twitter</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <!-- second line -->\r\n");
      out.write("\t    <div id=\"about\" class=\"row\">\r\n");
      out.write("\t        <p class=\"eng\">re:flex</p>\r\n");
      out.write("\t        <p>대표:유찬호<span class=\"bar\"></span>사업자등록번호:419-87-00807<span class=\"bar\"></span>통신판매업신고:제 2017-서울마포-2273호</p>\r\n");
      out.write("\t        <p>주소: 서울특별시 마포구 동교동 203-43 4층<span class=\"bar\"></span>대표전화:1566-6813<span class=\"bar\"></span>FAX:070-7848-0818<span class=\"bar\"></span>이메일:reflex@naver.com</p>\r\n");
      out.write("\t        <p>개인정보관리책임자:유찬호</p>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div id=\"copyright\" class=\"line-style\"><span>ⓒ</span>2019 re:flex</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
