/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-29 17:18:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.faq;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.*;

public final class faqReparation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1577639837852L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1577465951749L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
 
	//로그인한 경우
	Member memberLoggedIn= (Member)session.getAttribute("memberLoggedIn");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>re:flex</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Libre+Barcode+128+Text|Monoton|Permanent+Marker|Righteous|Seymour+One|Stalinist+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\"> <!-- 부트스트랩 -->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/mypage.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/header.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"container-fluid navbar-fixed-top\">\r\n");
      out.write("        <div id=\"header-wrapper\" class=\"row\">\r\n");
      out.write("            <div id=\"logo\" class=\"col-md-4\">\r\n");
      out.write("                <h1 class=\"eng\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">re:flex</a></h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"search\" class=\"col-md-4\">\r\n");
      out.write("                <h2 class=\"sr-only\">상품 검색</h2>\r\n");
      out.write("                <form action=\"\">\r\n");
      out.write("                    <button type=\"submit\" id=\"btn-search\" aria-label=\"search products\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <input type=\"search\" name=\"search\" placeholder=\"검색\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"menu\" class=\"col-md-4\">\r\n");
      out.write("                <ul class=\"list-unstyled list-inline text-right\">\r\n");
      out.write("                    ");
if(memberLoggedIn==null){ 
      out.write("\r\n");
      out.write("\t                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\r\n");
      out.write("\t                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\r\n");
      out.write("                    ");

                    	}
                    	else{
                    
      out.write("\r\n");
      out.write("\t                    <li><span class=\"strong\">");
      out.print(memberLoggedIn.getMemberName());
      out.write("</span>님</li>                    \r\n");
      out.write("\t                    <li>\r\n");
      out.write("\t                    \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">로그아웃</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("             \r\n");
      out.write("\t                    </li>\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <h2 class=\"sr-only\">장바구니</h2>\r\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberCart\" aria-label=\"cart\"><span class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <button type=\"button\"  id=\"btn-sidemenu\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-list\" aria-hidden=\"true\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- side menu -->\r\n");
      out.write("                <!-- level1 -->\r\n");
      out.write("                <div id=\"sidemenu-closeLayer\">\r\n");
      out.write("                <nav id=\"level1-sidemenu\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header></header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li id=\"recommended\" data-target=\"#level2-recommended\"><a href=\"#\">이럴 때 빌려봐<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("                        ");
 if(memberLoggedIn != null  && "admin".equals(memberLoggedIn.getMemberId())){ 
      out.write("\r\n");
      out.write("                        \t<li id=\"adminPage\" data-target=\"#level2-adminPage\"><a href=\"#\">관리자페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 }
                        	else{ 
                        
      out.write("\r\n");
      out.write("                        \t<li id=\"mypage\" data-target=\"#level2-mypage\"><a href=\"#\">마이페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/faq/faqBoard\">고객서비스(FAQ)</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/faq/faqIndex\">re:flex 소개</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- level2: 이럴때빌려봐 -->\r\n");
      out.write("                <nav id=\"level2-recommended\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                        \t<span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                              이럴 때 빌려봐\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT01\">반려동물과 함께 할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT02\">육아할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT03\">파티할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT04\">운동할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT05\">여행갈 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT06\">캠핑갈 때</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- level2: 마이페이지 / 로그인 안했으면 경고창 -->\r\n");
      out.write("                \r\n");
      out.write("                <nav id=\"level2-mypage\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                            마이페이지\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    \r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOrderList\">주문조회</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlist\">위시리스트</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalIng\">계약중인 렌탈</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalFin\">종료중인 렌탈</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypagePoint\">포인트 확인</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageReview\">이용후기 내역</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOneToOne\">1:1문의 내역</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberUpdate\">회원정보 수정</a></li>\r\n");
      out.write("                        <li><a href=\"\">회원정보 탈퇴</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <nav id=\"level2-adminPage\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                    \r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                            관리자페이지\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"#\">상품관리</a></li>\r\n");
      out.write("                        <li><a href=\"#\">주문관리</a></li>\r\n");
      out.write("                        <li><a href=\"#\">회원관리</a></li>\r\n");
      out.write("                 \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid contents none-nav\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-1\"></div>\r\n");
      out.write("                <div class=\"col-md-10 content-wrapper\">\r\n");
      out.write("                        <div id=\"wrapper\" class=\"row\">\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <!-- 헤더 -->\r\n");
      out.write("                            <div class=\"col-md-12\">\r\n");
      out.write("                                <div class=\"inner center-block\">\r\n");
      out.write("                                    <p id=\"text\">미리 알면 안심되는</p>\r\n");
      out.write("                                    <p id=\"text2\"><strong>케어존 & 배상금 기준</strong></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 컨텐트 1-->\r\n");
      out.write("                        <div id=\"block1\" class=\"row\">\r\n");
      out.write("                            <div class=\"clo-md-6\">\r\n");
      out.write("                                <p id=\"text3\"><strong>마음 놓고 쓰려면</strong></p>\r\n");
      out.write("                                <p id=\"text4\"><strong>케어존 숙지</strong></p>\r\n");
      out.write("                                <div class=\"circle1\"></div>\r\n");
      out.write("                                <div class=\"circle2\"></div>\r\n");
      out.write("                                <div class=\"circle3\"></div>\r\n");
      out.write("                                <div class=\"circle4\"></div>\r\n");
      out.write("                                <div class=\"circle5\"></div>\r\n");
      out.write("                                <div class=\"circle6\"></div>\r\n");
      out.write("                                <div id=\"text5\">\r\n");
      out.write("                                    <p>리플렉스 케어존은 사용하다 보면 자연스럽게 생기는 <br>\r\n");
      out.write("                                    생활 스크래치나 세탁 가능한 오염 등을 포함합니다. <br>\r\n");
      out.write("                                    안심하고 즐겨주세요! <br><br><br>단, 심한 훼손·분실 시에는 <strong>배상금*</strong>이 청구될 수 있습니다.</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 컨텐트 2-->\r\n");
      out.write("                        <div id=\"block2\" class=\"row\">\r\n");
      out.write("                            <div class=\"clo-md-6\">\r\n");
      out.write("                                <div class=\"inner\">\r\n");
      out.write("                                    <p id=\"text6\"><strong>배상금 기준*</strong></p>\r\n");
      out.write("                                    <table border=\"1\">\r\n");
      out.write("                                        <thead>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th>구분</th>\r\n");
      out.write("                                                <th>내용(예시)</th>\r\n");
      out.write("                                                <th>고객 배상금</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                        <!-- tbody>tr>td*3 -->\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td rowspan=\"4\" id=\"first-td\">가방</td>\r\n");
      out.write("                                                <td>전문 수선으로 복원 가능한 오염 및 스크래치</td>\r\n");
      out.write("                                                <td>50,000~200,000원</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>부착된 구성품(나사, 지퍼 손잡이, 스터드 등) 분실 또는 손상</td>\r\n");
      out.write("                                                <td>30,000~100,000원</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>구성품(스트랩, 참 등) 분실</td>\r\n");
      out.write("                                                <td>50,000~300,000원</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>분실 또는 수선 불가능한 오염(볼펜,화장품) 찢김, 훼손</td>\r\n");
      out.write("                                                <td>구매가 * 배상</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                    \r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td rowspan=\"5\" id=\"first-td\">시계/ <br> 액세서리</td>\r\n");
      out.write("                                                <td>폴리싱이 필요한 정도의 깊은 스크래치</td>\r\n");
      out.write("                                                <td>50,000~100,000원</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>오브제 손상, 분실</td>\r\n");
      out.write("                                                <td>부품 비용 실비 청구</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>전문 수선 필요한 밴드 끊어짐</td>\r\n");
      out.write("                                                <td>부품 비용 실비 청구</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>시계 유리 깨짐, 문자판 훼손, 시계 본체 침수</td>\r\n");
      out.write("                                                <td>구매가 * 배상</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>분실 또는 수선 불가능한 오염, 찢김, 깨짐, 훼손</td>\r\n");
      out.write("                                                <td>구매가 * 배상</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                        <tfoot>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td rowspan=\"4\" id=\"first-td\">의류</td>\r\n");
      out.write("                                                <td>전문 수선 필요한 밴드 끊어짐</td>\r\n");
      out.write("                                                <td>20,000원</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>부착된 액세서리 또는 원단 손상(울트임, 경미한 찢김 등)</td>\r\n");
      out.write("                                                <td>50,000~200,000원</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>구성품(벨트,브로치,리본 등) 분실</td>\r\n");
      out.write("                                                <td>50,000~200,000원</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>분실 또는 세탁/수선 불가능한 오염, 찢김, 훼손</td>\r\n");
      out.write("                                                <td>구매가 * 배상</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                    \r\n");
      out.write("                                        </tfoot>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-1\"></div>\r\n");
      out.write("\r\n");
      out.write("                <style>\r\n");
      out.write("                    /* 멤버십 */\r\n");
      out.write("                    #wrapper{width: 1500px; height:500px; margin: 0 auto; margin-bottom: 50px;}\r\n");
      out.write("                    #wrapper>div{height: 100%; background:purple; }\r\n");
      out.write("                    #block1{width: 1000px; height:500px; margin: 0 auto; margin-bottom: 250px;}\r\n");
      out.write("                    #block1>div{height: 100%; background:white; }\r\n");
      out.write("                    #block2{width: 1000px; margin: 0 auto; margin-top:90px; margin-bottom:500px;}\r\n");
      out.write("                    #block2>div{height: 100%; background:white; }\r\n");
      out.write("                \r\n");
      out.write("                    #text{text-align:center; font-size:25px; color:white; margin-top: 150px;}\r\n");
      out.write("                    #text2{text-align:center; font-size:45px; color:white; margin-top:20px;}\r\n");
      out.write("                    #text3{text-align:center; font-size:25px;}\r\n");
      out.write("                    #text4{text-align:center; font-size:30px; color:purple}\r\n");
      out.write("                    #text5{text-align:center; font-size:17px; margin-top:60px;}\r\n");
      out.write("                    #text6{text-align:center; font-size:30px; margin-bottom:50px; margin-top:100px;}\r\n");
      out.write("                \r\n");
      out.write("                    .circle1{border: 1px solid; width:200px; height:200px; -webkit-border-radius:100px; -moz-border-radius:100px; margin-top: 50px; margin-left:150px;}\r\n");
      out.write("                    .circle2{border: 1px solid; width:200px; height:200px; -webkit-border-radius:100px; -moz-border-radius:100px; margin-top: -200px; margin-left:400px;}\r\n");
      out.write("                    .circle3{border: 1px solid; width:200px; height:200px; -webkit-border-radius:100px; -moz-border-radius:100px; margin-top: -200px; margin-left: 650px;}\r\n");
      out.write("                    .circle4{border: 1px solid; width:200px; height:200px; -webkit-border-radius:100px; -moz-border-radius:100px; margin-top: 20px; margin-left:150px;}\r\n");
      out.write("                    .circle5{border: 1px solid; width:200px; height:200px; -webkit-border-radius:100px; -moz-border-radius:100px; margin-top: -200px; margin-left:400px;}\r\n");
      out.write("                    .circle6{border: 1px solid; width:200px; height:200px; -webkit-border-radius:100px; -moz-border-radius:100px; margin-top: -200px; margin-left:650px;}\r\n");
      out.write("                    \r\n");
      out.write("                    table{width: 80%; margin-left:auto; margin-right:auto;}\r\n");
      out.write("                    th{color:purple; text-align: center; font-size: 18px;}\r\n");
      out.write("                    #first-td{color:purple; text-align: center; font-size: 18px;}\r\n");
      out.write("                    th{width:100px; height:70px;}\r\n");
      out.write("                    td{height:70px;}\r\n");
      out.write("                </style>\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 맨위로 이동 버튼 -->\r\n");
      out.write("    <div id=\"go-to-top\" class=\"btn-bottom\">\r\n");
      out.write("        <button type=\"button\" id=\"btn-gotop\" class=\"center-block\">맨 위로 이동</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"container-fluid\">\r\n");
      out.write("\t    <div class=\"line-style\"></div>\r\n");
      out.write("\t    <!-- first line -->\r\n");
      out.write("\t    <div id=\"footer-menu\" class=\"row\">\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>회사소개</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">정책안내</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>고객서비스</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">1:1문의</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">주문현황</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>문의하기</header>\r\n");
      out.write("\t            <p id=\"q-call\" class=\"lead\">1577-1577</p>\r\n");
      out.write("\t            <p id=\"q-email\" class=\"lead\">reflex@naver.com</p>\r\n");
      out.write("\t            <p>평일 10:00~18:00</p>\r\n");
      out.write("\t            <p>주말 및 공휴일 휴무</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>SNS</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">Facebook</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">Instagram</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">Twitter</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <!-- second line -->\r\n");
      out.write("\t    <div id=\"about\" class=\"row\">\r\n");
      out.write("\t        <p class=\"eng\">re:flex</p>\r\n");
      out.write("\t        <p>대표:유찬호<span class=\"bar\"></span>사업자등록번호:419-87-00807<span class=\"bar\"></span>통신판매업신고:제 2017-서울마포-2273호</p>\r\n");
      out.write("\t        <p>주소: 서울특별시 마포구 동교동 203-43 4층<span class=\"bar\"></span>대표전화:1566-6813<span class=\"bar\"></span>FAX:070-7848-0818<span class=\"bar\"></span>이메일:reflex@naver.com</p>\r\n");
      out.write("\t        <p>개인정보관리책임자:유찬호</p>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div id=\"copyright\" class=\"line-style\"><span>ⓒ</span>2019 re:flex</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
