/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-07 23:50:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Arrays;
import java.sql.Date;
import item.model.vo.Item;
import item.model.vo.ItemImage;
import java.util.Map;
import order.model.vo.OrderDetail;
import java.util.List;
import java.text.DecimalFormat;
import member.model.vo.*;

public final class mypageOrderList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1578438112015L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1578438112430L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("item.model.vo.ItemImage");
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("item.model.vo.Item");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("order.model.vo.OrderDetail");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	//주문번호
	List<String> orderNoList = (List<String>)request.getAttribute("orderNoList");
	//주문번호에 담긴 상품내역들
	Map<String, List<OrderDetail>> orderListByOrderNo = (Map<String, List<OrderDetail>>)request.getAttribute("orderListByOrderNo");
	//상품내역들의 대여 시작일, 반납일
	Map<String, List<Date[]>> rentDateMap = (Map<String, List<Date[]>>)request.getAttribute("rentDateMap");
	
	//상품 사진
	List<Integer> itemNoList = (List<Integer>)request.getAttribute("itemNoList");
	Map<Integer, List<ItemImage>> imgMap = (Map<Integer, List<ItemImage>>)request.getAttribute("imgMap");
	
	int totalPage = (int)request.getAttribute("totalPage");
	
	//js tr태그 추가용: 주문번호당 몇 개 상품 들어있는지
	int[] eaArr = new int[orderNoList.size()];
	
	//주문현황 상태 카운트용
	int os02 = 0; //배송준비중
	int os03 = 0; //배송중
	int os04 = 0; //배송완료
	int ocNum = 0; //취소반품교환
	if(orderListByOrderNo!=null && !orderListByOrderNo.isEmpty()){
	    for(int i=0; i<orderNoList.size(); i++){
	    	String orderNo = orderNoList.get(i); //주문번호
	    	List<OrderDetail> odList = orderListByOrderNo.get(orderNo); //한 건의 주문안에 담겨있는 주문상품내역리스트
	    	System.out.println("odList"+odList);
	    	eaArr[i] = odList.get(0).getOrderTotalItemEa(); //한 건의 주문에 담겨있는 상품 수 
	    	
	    	for(int j=0; j<odList.size(); j++){
	    		OrderDetail od = odList.get(j);
	    		String osNo = od.getOrderStatusNo(); //주문상태번호
	    		String ccNo = od.getOrderCancelNo(); //주문취소번호
	    		if("OS02".equals(osNo)) os02++;
	    		else if("OS03".equals(osNo)) os03++;
	    		else if("OS04".equals(osNo)) os04++;
				
	    		if(ccNo!=null) ocNum++;
	    	}
	    }
	}
	

      out.write('\n');
      out.write("\n");
      out.write("   \n");
      out.write("   \n");
      out.write("   ");
 
   		//로그인한 경우
   		Member memberLoggedIn= (Member)session.getAttribute("memberLoggedIn");

   
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>re:flex</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Libre+Barcode+128+Text|Monoton|Permanent+Marker|Righteous|Seymour+One|Stalinist+One&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\"> <!-- 부트스트랩 -->\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/mypage.css\" rel=\"stylesheet\">\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/header.js\"></script>\n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header class=\"container-fluid navbar-fixed-top\">\n");
      out.write("        <div id=\"header-wrapper\" class=\"row\">\n");
      out.write("            <div id=\"logo\" class=\"col-md-4\">\n");
      out.write("                <h1 class=\"eng\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">re:flex</a></h1>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"search\" class=\"col-md-4\">\n");
      out.write("                <h2 class=\"sr-only\">상품 검색</h2>\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/item/itemSearch\">\n");
      out.write("                    <button type=\"submit\" id=\"btn-search\" aria-label=\"search products\">\n");
      out.write("                        <span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"></span>\n");
      out.write("                    </button>\n");
      out.write("                    <input type=\"search\" name=\"search\" placeholder=\"검색\">\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"menu\" class=\"col-md-4\">\n");
      out.write("                <ul class=\"list-unstyled list-inline text-right\">\n");
      out.write("                    ");
if(memberLoggedIn==null){ 
      out.write("\n");
      out.write("                    <li class=\"login-hide\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\n");
      out.write("                    <li class=\"login-hide\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\n");
      out.write("                    ");
}
                    else{
                    
      out.write("\n");
      out.write("\n");
      out.write("\t                <li><span class=\"strong\">");
      out.print(memberLoggedIn.getMemberName());
      out.write("</span>님</li>                    \n");
      out.write("\n");
      out.write("\t                <li>\n");
      out.write("\t                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">로그아웃</a>\n");
      out.write("\t                </li>\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t");
if(memberLoggedIn !=null && !"admin".equals(memberLoggedIn.getMemberId())) {
      out.write("\n");
      out.write("                    <li>\n");
      out.write("                        <h2 class=\"sr-only\">장바구니</h2>\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberCart?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" aria-label=\"cart\"><span class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span></a>\n");
      out.write("                    </li>\n");
      out.write("                    ");
} 
      out.write("\n");
      out.write("                    <li>\n");
      out.write("                        <button type=\"button\"  id=\"btn-sidemenu\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-list\" aria-hidden=\"true\"></span>\n");
      out.write("                        </button>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <!-- side menu -->\n");
      out.write("                <!-- level1 -->\n");
      out.write("                <div id=\"sidemenu-closeLayer\">\n");
      out.write("                <nav id=\"level1-sidemenu\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header></header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li id=\"recommended\" data-target=\"#level2-recommended\"><a href=\"#\">이럴 때 빌려봐<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("                        ");
 
                        	//관리자가 로그인한 경우
                        	if(memberLoggedIn != null && "admin".equals(memberLoggedIn.getMemberId())){ 
                        
      out.write("\n");
      out.write("                        \t<li id=\"adminPage\" data-target=\"#level2-adminPage\"><a href=\"#\">관리자페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("\t\t\t\t\t\t");
 
							} 
                        	//로그인한 회원이 있는 경우 마이페이지 메뉴 
                        	else if(memberLoggedIn!=null && !("admin".equals(memberLoggedIn.getMemberId()))){
						
      out.write("\n");
      out.write("                        \t<li id=\"mypage\" data-target=\"#level2-mypage\"><a href=\"#\">마이페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("                        ");

	                        }
                        	//로그인 안했으면 로그인, 회원가입 메뉴 보이게
							else{
                        
      out.write("\n");
      out.write("                        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\n");
      out.write("                        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\n");
      out.write("                        ");

							}
                        
      out.write("\n");
      out.write("                        <li><a href=\"#\">고객서비스(FAQ)</a></li>\n");
      out.write("                        <li><a href=\"#\">re:flex 소개</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <!-- level2: 이럴때빌려봐 -->\n");
      out.write("                <nav id=\"level2-recommended\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header class=\"text-center\">\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\n");
      out.write("                        \t<span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("                              이럴 때 빌려봐\n");
      out.write("                        </button>\n");
      out.write("                    </header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT01\">반려동물과 함께 할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT02\">육아할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT03\">파티할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT04\">운동할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT05\">여행갈 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT06\">캠핑갈 때</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <!-- level2: 마이페이지 -->\n");
      out.write("                ");

                	if(memberLoggedIn != null){
                
      out.write("\n");
      out.write("                <nav id=\"level2-mypage\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header class=\"text-center\">\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("                            마이페이지\n");
      out.write("                        </button>\n");
      out.write("                    </header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOrderList?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">주문조회</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlist?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">위시리스트</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalIng?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">계약중인 렌탈</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalFin?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">종료된 렌탈</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypagePoint?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">포인트 확인</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageReview?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">이용후기 내역</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOneToOne?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">1:1문의 내역</a></li>\n");
      out.write("                   \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberUpdate?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">회원정보 수정</a></li> \n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberDelete?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">회원정보 탈퇴</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                ");

                	}
                
      out.write("\n");
      out.write("\n");
      out.write("                \n");
      out.write("\n");
      out.write("                <nav id=\"level2-adminPage\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header class=\"text-center\">\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("                            관리자페이지\n");
      out.write("                        </button>\n");
      out.write("                    </header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/itemEnroll\">상품등록</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/itemSearch\">상품조회</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/rentalList\">렌탈내역</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/orderOutline\">판매현황</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/orderList\">배송관리</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/member/memberQna\">1:1문의관리</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/member/memberSearch\">회원조회</a></li>\n");
      out.write("\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>");
      out.write("\n");
      out.write("<script>\n");
      out.write("document.addEventListener('DOMContentLoaded', function(){\n");
      out.write("\tplusTdTag(); //주문번호td태그 추가 \n");
      out.write("\t\n");
      out.write("});\n");
      out.write("function plusTdTag(){\n");
      out.write("\tlet trArr = document.querySelectorAll(\".orderRow\");\n");
      out.write("\tlet plus = 1; //비교 클래스값\n");
      out.write("\tlet cnt = 0; //같은 주문번호의 tr이 몇 행있는지\n");
      out.write("\t\n");
      out.write("\ttrArr.forEach(function(obj, idx){\n");
      out.write("\t\tlet strArr = obj.className.split(\" \");\n");
      out.write("\t\tif(strArr[1]===cnt){\n");
      out.write("\t\t\tlet sameTrArr = new Array();\n");
      out.write("\t\t\tsameTrArr.push(this);\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("}\n");
      out.write("function goReview(btn, yn, odNo, itemNo){\n");
      out.write("\tlet val = btn.value;\n");
      out.write("\t\n");
      out.write("\t//구매후기 버튼 클릭: 주문상태 OS04일 경우만\n");
      out.write("\tif(yn!==\"N\" || val===\"OS05\") alert(\"이미 구매후기를 작성한 상품입니다.\");\n");
      out.write("\telse if(val===\"OS04\" && yn===\"N\"){\n");
      out.write("\t\tif(!confirm(\"구매후기를 작성하시겠습니까? \")) return;\n");
      out.write("\t\t\n");
      out.write("\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageReviewForm?itemNo=\"+itemNo+\"&orderDetailNo=\"+odNo;\n");
      out.write("\t}\n");
      out.write("\telse if(val===\"OS01\" || val===\"OS02\" || val===\"OS03\"){\n");
      out.write("\t\talert(\"구매후기는 배송완료일 때만 작성가능합니다.\");\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("function cancelOrder(btn, odNo, itemNo, optNo, memId){\n");
      out.write("\tlet val = btn.value;\n");
      out.write("\t\n");
      out.write("\t//주문완료, 배송준비중일 때만 취소가능\n");
      out.write("\tif(val===\"OS01\" || val===\"OS02\"){\n");
      out.write("\t\tif(!confirm(\"주문을 취소하시겠습니까?\")) return;\n");
      out.write("\t\t\t\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/order/orderCancel\",\n");
      out.write("\t\t\ttype: \"post\",\n");
      out.write("\t\t\tdata: {\n");
      out.write("\t\t\t\todNo: odNo,\n");
      out.write("\t\t\t\titemNo: itemNo,\n");
      out.write("\t\t\t\toptNo: optNo,\n");
      out.write("\t\t\t\tmemberId: memId\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tdataType: \"json\",\n");
      out.write("\t\t\tsuccess: data => {\n");
      out.write("\t\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\tif(data.result===1)\n");
      out.write("\t\t\t\t\talert(\"주문이 정상적으로 취소되었습니다.\");\n");
      out.write("\t\t\t\telse\n");
      out.write("\t\t\t\t\talert(\"주문이 취소되지 않았습니다.\\n다시 시도해 주세요.\");\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\twindow.location.reload();\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror: (jqxhr, textStatus, errorThrown)=>{\n");
      out.write("\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t\t} \n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\telse{\n");
      out.write("\t\talert(\"주문취소는 배송시작 전까지만 가능합니다.\");\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("function exchangeItem(btn, odNo, itemNo, optNo, memId){\n");
      out.write("\tlet val = btn.value;\n");
      out.write("\t\n");
      out.write("\t//배송완료, 구매확정일 때만 교환가능\n");
      out.write("\tif(val===\"OS04\" || val===\"OS05\"){\n");
      out.write("\t\tif(!confirm(\"상품을 교환하시겠습니까?\")) return;\n");
      out.write("\t\t\t\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/order/exchangeItem\",\n");
      out.write("\t\t\ttype: \"post\",\n");
      out.write("\t\t\tdata: {\n");
      out.write("\t\t\t\todNo: odNo,\n");
      out.write("\t\t\t\titemNo: itemNo,\n");
      out.write("\t\t\t\toptNo: optNo,\n");
      out.write("\t\t\t\tmemberId: memId\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tdataType: \"json\",\n");
      out.write("\t\t\tsuccess: data => {\n");
      out.write("\t\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\tif(data.result===1)\n");
      out.write("\t\t\t\t\talert(\"상품교환 신청이 정상적으로 접수되었습니다.\\n반납일이 10일 추가되었으니 확인해 주세요.\");\n");
      out.write("\t\t\t\telse\n");
      out.write("\t\t\t\t\talert(\"상품교환 신청이 접수되지 않았습니다.\\n다시 시도해 주세요.\");\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\twindow.location.reload();\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror: (jqxhr, textStatus, errorThrown)=>{\n");
      out.write("\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t\t} \n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\telse{\n");
      out.write("\t\talert(\"상품교환은 배송완료 후부터 가능합니다.\");\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("}\n");
      out.write("function cancelRent(btn, odNo, itemNo, optNo, memId){\n");
      out.write("\tlet val = btn.value;\n");
      out.write("\t\n");
      out.write("\t//배송완료, 구매확정일 때만 렌탈해지가능\n");
      out.write("\tif(val===\"OS04\" || val===\"OS05\"){\n");
      out.write("\t\tif(!confirm(\"렌탈을 해지하시겠습니까?\")) return;\n");
      out.write("\t\t\t\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/order/cancelRent\",\n");
      out.write("\t\t\ttype: \"post\",\n");
      out.write("\t\t\tdata: {\n");
      out.write("\t\t\t\todNo: odNo,\n");
      out.write("\t\t\t\titemNo: itemNo,\n");
      out.write("\t\t\t\toptNo: optNo,\n");
      out.write("\t\t\t\tmemberId: memId\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tdataType: \"json\",\n");
      out.write("\t\t\tsuccess: data => {\n");
      out.write("\t\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\tif(data.result===1)\n");
      out.write("\t\t\t\t\talert(\"렌탈해지 신청이 정상적으로 접수되었습니다.\\n반납일이 오늘로부터 5일 뒤 종료됩니다.\");\n");
      out.write("\t\t\t\telse \n");
      out.write("\t\t\t\t\talert(\"렌탈해지 신청이 접수되지 않았습니다.\\n다시 시도해 주세요.\");\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\twindow.location.reload();\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror: (jqxhr, textStatus, errorThrown)=>{\n");
      out.write("\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t\t} \n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\telse{\n");
      out.write("\t\talert(\"렌탈해지는 배송완료 후부터 가능합니다.\");\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("function checkByPeriod(btn, val){\n");
      out.write("\tlet btnLiArr = document.querySelectorAll(\".btn-li\");\n");
      out.write("\tlet parentLi = btn.parentNode;\n");
      out.write("\n");
      out.write("\t//.sel을 갖고 있으면 삭제 \n");
      out.write("\tbtnLiArr.forEach(function(obj, idx){\n");
      out.write("\t\tif(obj.className.indexOf('sel')){\n");
      out.write("\t\t\tobj.classList.remove('sel');\n");
      out.write("\t\t};\n");
      out.write("\t});\n");
      out.write("\t//현재 클릭한 버튼에만 .sel 추가\n");
      out.write("\tparentLi.classList.toggle('sel');\n");
      out.write("\t\n");
      out.write("\t//1개월 검색\n");
      out.write("\tif(val===1){\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOrderListByOneM?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\",\n");
      out.write("\t\t\ttype: \"get\",\n");
      out.write("\t\t\tdataType: \"html\",\n");
      out.write("\t\t\tsuccess: function(data){\n");
      out.write("\t\t\t\tconsole.log(data)\n");
      out.write("\n");
      out.write("\t\t\t\t$(\"#order-list\").html(data);\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror: function(jqxhr,textStatus,errorThrown){\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패\",jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\t//3개월 검색\n");
      out.write("\telse if(val===3){\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOrderListByThreeM?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\",\n");
      out.write("\t\t\ttype: \"get\",\n");
      out.write("\t\t\tdataType: \"html\",\n");
      out.write("\t\t\tsuccess: function(data){\n");
      out.write("\t\t\t\tconsole.log(data)\n");
      out.write("\n");
      out.write("\t\t\t\t$(\"#order-list\").html(data);\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror: function(jqxhr,textStatus,errorThrown){\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패\",jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\t//6개월 검색\n");
      out.write("\telse if(val===6){\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOrderListBySixM?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\",\n");
      out.write("\t\t\ttype: \"get\",\n");
      out.write("\t\t\tdataType: \"html\",\n");
      out.write("\t\t\tsuccess: function(data){\n");
      out.write("\t\t\t\tconsole.log(data)\n");
      out.write("\n");
      out.write("\t\t\t\t$(\"#order-list\").html(data);\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror: function(jqxhr,textStatus,errorThrown){\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패\",jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\t//전체 검색\n");
      out.write("\telse{\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOrderListByAll?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\",\n");
      out.write("\t\t\ttype: \"get\",\n");
      out.write("\t\t\tdataType: \"html\",\n");
      out.write("\t\t\tsuccess: function(data){\n");
      out.write("\t\t\t\tconsole.log(data)\n");
      out.write("\n");
      out.write("\t\t\t\t$(\"#order-list\").html(data);\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror: function(jqxhr,textStatus,errorThrown){\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패\",jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- page nav -->\n");
      out.write("<nav class=\"line-style page-nav\">\n");
      out.write("    <ul class=\"list-unstyled list-inline\">\n");
      out.write("        <li class=\"go-home\">\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">메인</a>\n");
      out.write("            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"go-boxmenu\">\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/common/boxMenu?level1=mypage\">마이페이지</a>\n");
      out.write("            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\n");
      out.write("        </li>\n");
      out.write("        <li>주문현황</li>\n");
      out.write("    </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<!-- 주문현황 상태 -->\n");
      out.write("<div class=\"container-fluid contents\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-md-1\"></div>\n");
      out.write("        <div class=\"col-md-10 content-wrapper\">\n");
      out.write("            <h2 class=\"sr-only\">주문현황</h2>\n");
      out.write("            <!-- 주문상태 보기 -->\n");
      out.write("            <section id=\"parcel\" class=\"my-header\">\n");
      out.write("                <h3 class=\"sr-only\">주문상태 보기</h3>\n");
      out.write("                <ul class=\"row list-unstyled list-inline\">\n");
      out.write("                    <li class=\"col-md-3 text-center\">배송준비중 <span class=\"em-blue\">");
      out.print(os02 );
      out.write("</span></li>\n");
      out.write("                    <li class=\"col-md-3 text-center\">배송중 <span class=\"em-blue\">");
      out.print(os03 );
      out.write("</span></li>\n");
      out.write("                    <li class=\"col-md-3 text-center\">배송완료 <span class=\"em-blue\">");
      out.print(os04 );
      out.write("</span></li>\n");
      out.write("                    <li class=\"col-md-3 text-center\">취소/반품/교환 <span class=\"em-blue\">");
      out.print(ocNum );
      out.write("</span></li>\n");
      out.write("                </ul>\n");
      out.write("            </section>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-1\"></div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 기간검색 -->\n");
      out.write("<div class=\"container-fluid line-style text-center\">\n");
      out.write("    <p class=\"strong\">기간검색</p>\n");
      out.write("</div>\n");
      out.write("<div class=\"container-fluid\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-md-1\"></div>\n");
      out.write("        <div class=\"col-md-10 content-wrapper\">\n");
      out.write("            <section class=\"my-header\">\n");
      out.write("                <h3 class=\"sr-only\">주문현황 기간검색하기</h3>\n");
      out.write("                <ul class=\"row list-inline list-unstyled\">\n");
      out.write("                    <li class=\"col-md-3 text-center btn-li\"><button type=\"button\" onclick=\"checkByPeriod(this, 1);\">1개월</button></li>\n");
      out.write("                    <li class=\"col-md-3 text-center btn-li sel\"><button type=\"button\" onclick=\"checkByPeriod(this, 3);\">3개월</button></li>\n");
      out.write("                    <li class=\"col-md-3 text-center btn-li\"><button type=\"button\" onclick=\"checkByPeriod(this, 6);\">6개월</button></li>\n");
      out.write("                    <li class=\"col-md-3 text-center btn-li\"><button type=\"button\" onclick=\"checkByPeriod(this, all);\">전체</button></li>\n");
      out.write("                </ul>\n");
      out.write("            </section>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-1\"></div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 주문현황 리스트 -->\n");
      out.write("<div class=\"container-fluid line-style text-center\">\n");
      out.write("    <p class=\"strong\">주문 상품 정보</p>\n");
      out.write("</div>\n");
      out.write("<div class=\"container-fluid\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-md-1\"></div>\n");
      out.write("        <div class=\"col-md-10 content-wrapper\">\n");
      out.write("            <section id=\"order-list\" class=\"list-wrapper\">\n");
      out.write("                <h3 class=\"sr-only\">주문현황 리스트</h3>\n");
      out.write("                <table id=\"odl-tbl\" class=\"text-center list-tbl\">\n");
      out.write("                \t<colgroup>\n");
      out.write("\t                    <col width=\"16%\">\n");
      out.write("\t                    <col width=\"35%\">\n");
      out.write("\t                    <col width=\"7%\">\n");
      out.write("\t                    <col width=\"16%\">\n");
      out.write("\t                    <col width=\"13%\">\n");
      out.write("\t                    <col width=\"13%\">\n");
      out.write("\t                </colgroup>\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th class=\"text-center\">주문번호[날짜]</th>\n");
      out.write("                            <th class=\"text-center\">상품정보</th>\n");
      out.write("                            <th class=\"text-center\">수량</th>\n");
      out.write("                            <th class=\"text-center\">렌탈기간</th>\n");
      out.write("                            <th class=\"text-center\">상태</th>\n");
      out.write("                            <th class=\"text-center\">변경</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                    ");

                    	if(orderListByOrderNo!=null && !orderListByOrderNo.isEmpty()){
                    		for(int i=0; i<orderNoList.size(); i++){
                    			String orderNo = orderNoList.get(i); //주문번호
                    			
                    			//한 건의 주문안에 담겨있는 주문상품내역리스트
                    			List<OrderDetail> odList = orderListByOrderNo.get(orderNo);
                    			//대여기간 리스트
                    			List<Date[]> dateList = rentDateMap.get(orderNo);

                    			for(int j=0; j<odList.size(); j++){
                    				OrderDetail od = odList.get(j); //하나의 주문상품내역
                    				Item item = od.getItem(); //그 안에 포함된 하나의 상품
                    				List<ItemImage> imgList = imgMap.get(item.getItemNo()); //그 상품의 이미지리스트
                    				
                    				//렌탈기간
        							int rentPeriod = 0;
        							if("RT01".equals(od.getRentOptNo())) rentPeriod = 7;
        							else if("RT02".equals(od.getRentOptNo())) rentPeriod = 14;
        							else rentPeriod = 30;
                    				
                    				//가격 ,찍기
                    				DecimalFormat dc = new DecimalFormat("###,###,###,###원");
                    				String dpEa = dc.format(od.getPriceByRentOptNo()*od.getItemQuantity());
                    				
                    				//대여기간
                    				Date[] dArr = dateList.get(j);
                    				
                    				//주문상태
                    				String orderStatus = "주문완료";
                    				if("OS02".equals(od.getOrderStatusNo())) orderStatus = "배송준비중";
                    				else if("OS03".equals(od.getOrderStatusNo())) orderStatus = "배송중";
                    				else if("OS04".equals(od.getOrderStatusNo())) orderStatus = "배송완료";
                    				else if("OS05".equals(od.getOrderStatusNo())) orderStatus = "구매확정";
                    
      out.write("\n");
      out.write("                        <tr class=\"orderRow ");
      out.print(i);
      out.write(' ');
      out.print(od.getOrderTotalItemEa());
      out.write(' ');
      out.print(orderNo);
      out.write(' ');
      out.print(od.getOrderDate());
      out.write("\">\n");
      out.write("                        \t<input type=\"hidden\" name=\"odListSize\" value=\"");
      out.print(odList.size());
      out.write("\" />\n");
      out.write("                            <td rowspan=\"\">\n");
      out.write("                                <p>");
      out.print(orderNo);
      out.write("</p>\n");
      out.write("                                <p>[");
      out.print(od.getOrderDate());
      out.write("]</p>\n");
      out.write("                            </td>\n");
      out.write("                            <td class=\"item-info\">\n");
      out.write("                                <a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemView?categoryNo=");
      out.print(item.getCategoryNo());
      out.write("&itemNo=");
      out.print(item.getItemNo());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/");
      out.print(item.getCategoryNo());
      out.write('/');
      out.print(imgList.get(0).getItemImageRenamed());
      out.write("\" class=\"pull-left\" alt=\"상품이미지\"></a>\n");
      out.write("                                <a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemView?categoryNo=");
      out.print(item.getCategoryNo());
      out.write("&itemNo=");
      out.print(item.getItemNo());
      out.write("\">\n");
      out.write("                                \t<p class=\"text-left pbrand\">");
      out.print(item.getItemBrand());
      out.write("</p>\n");
      out.write("                                \t<p class=\"text-left pname\">");
      out.print(item.getItemName());
      out.write("</p>\n");
      out.write("                                </a>\n");
      out.write("                                <p class=\"text-left price\">");
      out.print(dpEa);
      out.write(" /<span class=\"rent-period\"> ");
      out.print(rentPeriod );
      out.write("일</p>\n");
      out.write("                                <p class=\"pull-left rent-type\">일시납</p>\n");
      out.write("                            </td>\n");
      out.write("                            <td>");
      out.print(od.getItemQuantity());
      out.write("</td>\n");
      out.write("                            ");
 if(dArr[0]==null || dArr[1]==null){ 
      out.write("\n");
      out.write("                            \t<td>-</td>\n");
      out.write("                            ");
 
                            	}
                            	else{
                            
      out.write("\n");
      out.write("                           \t\t<td class=\"\">");
      out.print(dArr[0]);
      out.write('~');
      out.print(dArr[1]);
      out.write("</td>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                            <td class=\"order-status ");
      out.print(od.getOrderDetailNo());
      out.write("\">\n");
      out.write("                                <p class=\"ship-status\">");
      out.print(orderStatus);
      out.write("</p>\n");
      out.write("                                <button type=\"button\" id=\"btn-goReview\" class=\"btn-radius\" value=\"");
      out.print(od.getOrderStatusNo());
      out.write("\" onclick=\"goReview(this,'");
      out.print(od.getReviewYn());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(od.getOrderDetailNo());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(item.getItemNo());
      out.write("');\">구매후기</button>\n");
      out.write("                            </td>\n");
      out.write("                            <td class=\"item-change ");
      out.print(od.getOrderDetailNo());
      out.write("\">\n");
      out.write("                            \t");
 if(od.getOrderCancelNo()==null){ 
      out.write("\n");
      out.write("                                <ul class=\"list-unstyled text-center\">\n");
      out.write("                                    <li><button type=\"button\" id=\"btn-cancelOrder\" class=\"btn-radius\" value=\"");
      out.print(od.getOrderStatusNo());
      out.write("\" onclick=\"cancelOrder(this,'");
      out.print(od.getOrderDetailNo());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(item.getItemNo());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(od.getRentOptNo());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(od.getMemberId());
      out.write("');\">주문취소</button></li>\n");
      out.write("                                    <li><button type=\"button\" id=\"btn-exchangeItem\" class=\"btn-radius\" value=\"");
      out.print(od.getOrderStatusNo());
      out.write("\" onclick=\"exchangeItem(this,'");
      out.print(od.getOrderDetailNo());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(item.getItemNo());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(od.getRentOptNo());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(od.getMemberId());
      out.write("');\">상품교환</button></li>\n");
      out.write("                                    <li><button type=\"button\" id=\"btn-cancelRent\" class=\"btn-radius\" value=\"");
      out.print(od.getOrderStatusNo());
      out.write("\" onclick=\"cancelRent(this,'");
      out.print(od.getOrderDetailNo());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(item.getItemNo());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(od.getRentOptNo());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(od.getMemberId());
      out.write("');\">렌탈해지</button></li>\n");
      out.write("                                </ul>\n");
      out.write("                                ");
 } 
                            		else{ 
                                		String cancelNo = ("OC01".equals(od.getOrderCancelNo()))?"주문취소":("OC02".equals(od.getOrderCancelNo()))?"상품교환":"렌탈해지";
                                
      out.write("\n");
      out.write("                                \t");
      out.print(cancelNo );
      out.write("\n");
      out.write("                                ");
} 
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                    ");

                    			}
                    		}
                    	}
                    
      out.write("    \n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </section>\n");
      out.write("            <!-- 페이징바 -->\n");
      out.write("            ");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-1\"></div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 더보기 버튼 -->\n");
      out.write("<div id=\"go-to-top\" class=\"btn-bottom\">\n");
      out.write("    <button type=\"button\" id=\"btn-more\" class=\"center-block\" onclick=\"\">더 로드하기</button>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<footer class=\"container-fluid\">\n");
      out.write("\t    <div class=\"line-style\"></div>\n");
      out.write("\t    <!-- first line -->\n");
      out.write("\t    <div id=\"footer-menu\" class=\"row\">\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>회사소개</header>\n");
      out.write("\t            <ul class=\"list-unstyled\">\n");
      out.write("\t                <li><a href=\"#\">이용약관</a></li>\n");
      out.write("\t                <li><a href=\"#\">정책안내</a></li>\n");
      out.write("\t            </ul>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>고객서비스</header>\n");
      out.write("\t            <ul class=\"list-unstyled\">\n");
      out.write("\t                <li><a href=\"#\">FAQ</a></li>\n");
      out.write("\t                <li><a href=\"#\">1:1문의</a></li>\n");
      out.write("\t                <li><a href=\"#\">주문현황</a></li>\n");
      out.write("\t            </ul>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>문의하기</header>\n");
      out.write("\t            <p id=\"q-call\" class=\"lead\">1577-1577</p>\n");
      out.write("\t            <p id=\"q-email\" class=\"lead\">reflex@naver.com</p>\n");
      out.write("\t            <p>평일 10:00~18:00</p>\n");
      out.write("\t            <p>주말 및 공휴일 휴무</p>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>SNS</header>\n");
      out.write("\t            <ul class=\"list-unstyled\">\n");
      out.write("\t                <li><a href=\"#\">Facebook</a></li>\n");
      out.write("\t                <li><a href=\"#\">Instagram</a></li>\n");
      out.write("\t                <li><a href=\"#\">Twitter</a></li>\n");
      out.write("\t            </ul>\n");
      out.write("\t        </div>\n");
      out.write("\t    </div>\n");
      out.write("\t    <!-- second line -->\n");
      out.write("\t    <div id=\"about\" class=\"row\">\n");
      out.write("\t        <p class=\"eng\">re:flex</p>\n");
      out.write("\t        <p>대표:유찬호<span class=\"bar\"></span>사업자등록번호:419-87-00807<span class=\"bar\"></span>통신판매업신고:제 2017-서울마포-2273호</p>\n");
      out.write("\t        <p>주소: 서울특별시 마포구 동교동 203-43 4층<span class=\"bar\"></span>대표전화:1566-6813<span class=\"bar\"></span>FAX:070-7848-0818<span class=\"bar\"></span>이메일:reflex@naver.com</p>\n");
      out.write("\t        <p>개인정보관리책임자:유찬호</p>\n");
      out.write("\t    </div>\n");
      out.write("\t    <div id=\"copyright\" class=\"line-style\"><span>ⓒ</span>2019 re:flex</div>\n");
      out.write("\t</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
