/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-07 23:10:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import item.model.vo.Item;
import item.model.vo.ItemImage;
import member.model.vo.*;
import java.text.DecimalFormat;
import member.model.vo.*;
import member.model.service.*;
import java.util.*;

public final class memberCart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1578438112015L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1578438112430L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("member.model.service");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("item.model.vo.ItemImage");
    _jspx_imports_classes.add("item.model.vo.Item");
    _jspx_imports_classes.add("java.text.DecimalFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("   \n");
      out.write("   \n");
      out.write("   ");
 
   		//로그인한 경우
   		Member memberLoggedIn= (Member)session.getAttribute("memberLoggedIn");

   
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>re:flex</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Libre+Barcode+128+Text|Monoton|Permanent+Marker|Righteous|Seymour+One|Stalinist+One&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\"> <!-- 부트스트랩 -->\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/mypage.css\" rel=\"stylesheet\">\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/header.js\"></script>\n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header class=\"container-fluid navbar-fixed-top\">\n");
      out.write("        <div id=\"header-wrapper\" class=\"row\">\n");
      out.write("            <div id=\"logo\" class=\"col-md-4\">\n");
      out.write("                <h1 class=\"eng\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">re:flex</a></h1>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"search\" class=\"col-md-4\">\n");
      out.write("                <h2 class=\"sr-only\">상품 검색</h2>\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/item/itemSearch\">\n");
      out.write("                    <button type=\"submit\" id=\"btn-search\" aria-label=\"search products\">\n");
      out.write("                        <span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"></span>\n");
      out.write("                    </button>\n");
      out.write("                    <input type=\"search\" name=\"search\" placeholder=\"검색\">\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"menu\" class=\"col-md-4\">\n");
      out.write("                <ul class=\"list-unstyled list-inline text-right\">\n");
      out.write("                    ");
if(memberLoggedIn==null){ 
      out.write("\n");
      out.write("                    <li class=\"login-hide\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\n");
      out.write("                    <li class=\"login-hide\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\n");
      out.write("                    ");
}
                    else{
                    
      out.write("\n");
      out.write("\n");
      out.write("\t                <li><span class=\"strong\">");
      out.print(memberLoggedIn.getMemberName());
      out.write("</span>님</li>                    \n");
      out.write("\n");
      out.write("\t                <li>\n");
      out.write("\t                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">로그아웃</a>\n");
      out.write("\t                </li>\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t");
if(memberLoggedIn !=null && !"admin".equals(memberLoggedIn.getMemberId())) {
      out.write("\n");
      out.write("                    <li>\n");
      out.write("                        <h2 class=\"sr-only\">장바구니</h2>\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberCart?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" aria-label=\"cart\"><span class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span></a>\n");
      out.write("                    </li>\n");
      out.write("                    ");
} 
      out.write("\n");
      out.write("                    <li>\n");
      out.write("                        <button type=\"button\"  id=\"btn-sidemenu\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-list\" aria-hidden=\"true\"></span>\n");
      out.write("                        </button>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <!-- side menu -->\n");
      out.write("                <!-- level1 -->\n");
      out.write("                <div id=\"sidemenu-closeLayer\">\n");
      out.write("                <nav id=\"level1-sidemenu\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header></header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li id=\"recommended\" data-target=\"#level2-recommended\"><a href=\"#\">이럴 때 빌려봐<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("                        ");
 
                        	//관리자가 로그인한 경우
                        	if(memberLoggedIn != null && "admin".equals(memberLoggedIn.getMemberId())){ 
                        
      out.write("\n");
      out.write("                        \t<li id=\"adminPage\" data-target=\"#level2-adminPage\"><a href=\"#\">관리자페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("\t\t\t\t\t\t");
 
							} 
                        	//로그인한 회원이 있는 경우 마이페이지 메뉴 
                        	else if(memberLoggedIn!=null && !("admin".equals(memberLoggedIn.getMemberId()))){
						
      out.write("\n");
      out.write("                        \t<li id=\"mypage\" data-target=\"#level2-mypage\"><a href=\"#\">마이페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("                        ");

	                        }
                        	//로그인 안했으면 로그인, 회원가입 메뉴 보이게
							else{
                        
      out.write("\n");
      out.write("                        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\n");
      out.write("                        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\n");
      out.write("                        ");

							}
                        
      out.write("\n");
      out.write("                        <li><a href=\"#\">고객서비스(FAQ)</a></li>\n");
      out.write("                        <li><a href=\"#\">re:flex 소개</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <!-- level2: 이럴때빌려봐 -->\n");
      out.write("                <nav id=\"level2-recommended\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header class=\"text-center\">\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\n");
      out.write("                        \t<span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("                              이럴 때 빌려봐\n");
      out.write("                        </button>\n");
      out.write("                    </header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT01\">반려동물과 함께 할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT02\">육아할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT03\">파티할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT04\">운동할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT05\">여행갈 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT06\">캠핑갈 때</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <!-- level2: 마이페이지 -->\n");
      out.write("                ");

                	if(memberLoggedIn != null){
                
      out.write("\n");
      out.write("                <nav id=\"level2-mypage\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header class=\"text-center\">\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("                            마이페이지\n");
      out.write("                        </button>\n");
      out.write("                    </header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOrderList?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">주문조회</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlist?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">위시리스트</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalIng?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">계약중인 렌탈</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalFin?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">종료된 렌탈</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypagePoint?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">포인트 확인</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageReview?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">이용후기 내역</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOneToOne?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">1:1문의 내역</a></li>\n");
      out.write("                   \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberUpdate?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">회원정보 수정</a></li> \n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberDelete?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">회원정보 탈퇴</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                ");

                	}
                
      out.write("\n");
      out.write("\n");
      out.write("                \n");
      out.write("\n");
      out.write("                <nav id=\"level2-adminPage\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header class=\"text-center\">\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("                            관리자페이지\n");
      out.write("                        </button>\n");
      out.write("                    </header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/itemEnroll\">상품등록</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/itemSearch\">상품조회</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/rentalList\">렌탈내역</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/orderOutline\">판매현황</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/orderList\">배송관리</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/member/memberQna\">1:1문의관리</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/member/memberSearch\">회원조회</a></li>\n");
      out.write("\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	String memberId = "";
	if (memberLoggedIn == null) {
		memberId = " ";
	} else {
		memberId = memberLoggedIn.getMemberId();	
	}

	List<Cart> cartList = (List<Cart>)request.getAttribute("cartList");
	List<Integer> itemNoList = (List<Integer>)request.getAttribute("itemNoList");
	Map<Integer, List<ItemImage>> imgMap = (Map<Integer, List<ItemImage>>)request.getAttribute("imgMap");
	
	//총 가격 먼저 구해두기: 배송비 결정
	int rentPriceEa = 0; //priceByRentOptNo*수량
	int totalPrice = 0; //총 가격
	
	if (cartList != null && cartList.size() > 0) {
		for(int i=0; i<cartList.size(); i++){
			Cart cart = cartList.get(i);
	    	rentPriceEa = cart.getPriceByRentOptNo() * cart.getItemQuantity(); //가격*수량
			totalPrice += rentPriceEa; //총가격
		} 
	}

      out.write("\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/memberCart.js\"></script>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("\n");
      out.write("document.addEventListener('DOMContentLoaded', function(){\n");
      out.write("\tplusShipPrice(); //배송비 td 추가하기\n");
      out.write("\tshowTotalPrice(); //전체상품 가격보기\n");
      out.write("\tchkAll(); //체크박스 전체선택\n");
      out.write("\t\n");
      out.write("\t//선택주문 버튼 클릭한 경우\n");
      out.write("\t$(\"#btn-orderChk\").click(function(){\n");
      out.write("\t\tlet noArr = new Array(); //선택중인 카트번호 담을 배열\n");
      out.write("\t\t\n");
      out.write("\t\tfor (let i = 1; i < $('table tr').size(); i++) {\n");
      out.write("\t\t\tlet chk = $('table tr').eq(i).children().find('input[type=\"checkbox\"]').is(':checked');\n");
      out.write("\t\n");
      out.write("\t\t\tif (chk == true) {\n");
      out.write("\t\t\t\tlet cartNo = $('table tr').eq(i).find('input[name=\"cartNo\"]').val();\n");
      out.write("\t\t\t\tnoArr.push(cartNo);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/order/orderManyChk?memberId=");
      out.print(memberId);
      out.write("&cartNo=\"+noArr;\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t//전체주문 버튼 클릭한 경우\n");
      out.write("\t$(\"#btn-orderAll\").click(function(){\n");
      out.write("\t   \n");
      out.write("\t   location.href=\"");
      out.print(request.getContextPath());
      out.write("/order/orderManyAll?memberId=");
      out.print(memberId);
      out.write("\";\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("function plusShipPrice(){\n");
      out.write("\tlet fisrtCartRow = document.querySelector(\".cartRow:first-of-type\");\n");
      out.write("\t\n");
      out.write("\t//총 가격이 50000원 이상이면 배송비 무료\n");
      out.write("\tif(");
      out.print(totalPrice);
      out.write(">50000)\n");
      out.write("\t\t$(fisrtCartRow).append(\"<td rowspan='");
      out.print(cartList.size());
      out.write("' id='cart-shipPrice'>무료</td>\");\n");
      out.write("\t//50000원 미만이면 배송비 4000원\n");
      out.write("\telse\n");
      out.write("\t\t$(fisrtCartRow).append(\"<td rowspan='");
      out.print(cartList.size());
      out.write("' id='cart-shipPrice'>4,000원</td>\");\n");
      out.write("}\n");
      out.write("function showTotalPrice(){\n");
      out.write("\tlet dpEaArr = document.querySelectorAll(\".dpEa\"); //주문상품금액들\n");
      out.write("\tlet shipPrice = document.querySelector(\"#cart-shipPrice\").innerText; //배송비\n");
      out.write("\tlet sum = 0; //총 가격\n");
      out.write("\t\n");
      out.write("\t//바뀌게 될 전체상품 가격보기 변수들\n");
      out.write("\tlet totalDpEa = document.querySelector(\"#total-dpEa\"); //상품금액\n");
      out.write("\tlet totalShipPrice = document.querySelector(\"#total-shipPrice\"); //배송비\n");
      out.write("\tlet totalPrice = document.querySelector(\"#total-price\"); //결제예상금액\n");
      out.write("\t\n");
      out.write("\tdpEaArr.forEach(function(obj, idx){\n");
      out.write("\t\tlet price = obj.innerText;\n");
      out.write("\t\t\n");
      out.write("\t\tprice = price.replace(\",\", \"\").replace(\"원\", \"\")*1;\n");
      out.write("\t\tconsole.log(price);\n");
      out.write("\t\tsum += price;\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\ttotalDpEa.innerText = sum.toLocaleString()+\"원\"; //상품금액 변경\n");
      out.write("\t\n");
      out.write("\tif(shipPrice===\"4,000원\"){\n");
      out.write("\t\ttotalShipPrice.innerText = shipPrice; //배송비 변경\n");
      out.write("\t\t\n");
      out.write("\t\tshipPrice = shipPrice.replace(\",\", \"\").replace(\"원\", \"\")*1;\n");
      out.write("\t\tsum += shipPrice;\n");
      out.write("\t}\n");
      out.write("\telse{\n");
      out.write("\t\ttotalShipPrice.innerText = \"0원\"; //배송비 변경\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\ttotalPrice.innerText = sum.toLocaleString()+\"원\"; //결제예상금액 변경\n");
      out.write("}\n");
      out.write("\n");
      out.write("function chkAll(){\n");
      out.write("\tlet btnChkAll = document.querySelector(\".btn-chkAll\");\n");
      out.write("\tlet chkboxArr = document.querySelectorAll(\".item-chk>input\");\n");
      out.write("\t\n");
      out.write("\t//전체선택 버튼 클릭\n");
      out.write("\tbtnChkAll.addEventListener(\"click\", function(){\n");
      out.write("\t\tchkboxArr.forEach(function(obj, idx){\n");
      out.write("\t\t\tobj.checked = true;\n");
      out.write("\t\t});\t\n");
      out.write("\t});\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("<!-- page nav -->\n");
      out.write("<nav class=\"line-style page-nav\">\n");
      out.write("    <ul class=\"list-unstyled list-inline\">\n");
      out.write("        <li class=\"go-home\">\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">메인</a>\n");
      out.write("            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\n");
      out.write("        </li>\n");
      out.write("        <li>장바구니</li>\n");
      out.write("    </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<!-- 장바구니 -->\n");
      out.write("<div class=\"container-fluid contents\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-md-1\"></div>\n");
      out.write("        ");

        	if (cartList != null && cartList.size() > 0) {
        
      out.write("\n");
      out.write("        <div class=\"col-md-10 content-wrapper\">\n");
      out.write("            <h2 class=\"sr-only\">장바구니</h2>\n");
      out.write("            <!-- 장바구니 목록 -->\n");
      out.write("\t        <section class=\"cart-wrapper\">\n");
      out.write("\t            <h3 class=\"sr-only\">장바구니 목록 보기</h3>\n");
      out.write("\t            <table class=\"text-center list-tbl\">\n");
      out.write("\t                <colgroup>\n");
      out.write("\t                    <col width=\"5%\">\n");
      out.write("\t                    <col width=\"50%\">\n");
      out.write("\t                    <col width=\"15%\">\n");
      out.write("\t                    <col width=\"10%\">\n");
      out.write("\t                    <col width=\"10%\">\n");
      out.write("\t                    <col width=\"10%\">\n");
      out.write("\t                </colgroup>\n");
      out.write("\t                <thead>\n");
      out.write("\t                    <tr>\n");
      out.write("\t                        <th class=\"text-center item-chk\">\n");
      out.write("\t                            <input type=\"checkbox\" name=\"delAllCartlist\" id=\"th_checkAll\" onclick=\"checkAll();\"/>\n");
      out.write("\t                        </th>\n");
      out.write("\t                        <th class=\"text-center\">상품정보</th>\n");
      out.write("\t                        <th class=\"text-center\">수량</th>\n");
      out.write("\t                        <th class=\"text-center\">기간</th>\n");
      out.write("\t                        <th class=\"text-center\">주문상품금액</th>\n");
      out.write("\t                        <th class=\"text-center\">배송비</th>\n");
      out.write("\t                    </tr>\n");
      out.write("\t                </thead>\n");
      out.write("\t                <tbody>\n");
      out.write("\t\t\t\t\t");

						for (int i=0; i<cartList.size(); i++) {
							Cart cart = cartList.get(i);
							Item item = cart.getItem();
							List<ItemImage> imgList = imgMap.get(itemNoList.get(i));
							
							//렌탈기간
							int rentPeriod = 0;
							if("RT01".equals(cart.getRentOptNo())) rentPeriod = 7;
							else if("RT02".equals(cart.getRentOptNo())) rentPeriod = 14;
							else rentPeriod = 30;
							
							//가격 , 붙이기
							DecimalFormat dc = new DecimalFormat("###,###,###,###원");
							String pbyRentOptNo = dc.format(cart.getPriceByRentOptNo()); //1개가격
							String pEa = dc.format(cart.getPriceByRentOptNo()*cart.getItemQuantity()); // *수량
					
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t                    <tr class =\"cartRow\">\n");
      out.write("\t                        <td class=\"item-chk\">\n");
      out.write("\t                            <input type=\"checkbox\" name=\"delCartlist\" id=\"");
      out.print(item.getItemNo() );
      out.write("\" value=\"");
      out.print(cart.getPriceByRentOptNo() * cart.getItemQuantity() );
      out.write("\"/>\n");
      out.write("\t                        </td>\n");
      out.write("\t                        <td class=\"item-info\">\n");
      out.write("\t                            <a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemView?categoryNo=");
      out.print(item.getCategoryNo());
      out.write("&itemNo=");
      out.print(item.getItemNo());
      out.write("\">\n");
      out.write("\t                            \t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/");
      out.print(item.getCategoryNo());
      out.write('/');
      out.print(imgList.get(0).getItemImageRenamed());
      out.write("\" class=\"pull-left\" alt=\"상품이미지\">\n");
      out.write("\t                            </a>\n");
      out.write("\t                            <a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemView?categoryNo=");
      out.print(item.getCategoryNo());
      out.write("&itemNo=");
      out.print(item.getItemNo());
      out.write("\">\n");
      out.write("\t                                <p class=\"text-left pbrand\">");
      out.print(item.getItemBrand() );
      out.write("</p>\n");
      out.write("\t                                <p class=\"text-left pname\">");
      out.print(item.getItemName() );
      out.write("</p>\n");
      out.write("\t                            </a>\n");
      out.write("\t                            <p class=\"text-left price\">렌탈료 <span class=\"em-price\">");
      out.print(pbyRentOptNo);
      out.write("</span>/");
      out.print(rentPeriod);
      out.write("일</p>\n");
      out.write("\t                        </td>\n");
      out.write("\t                        <td>\n");
      out.write("\t                            <div id=\"sel-amount\">\n");
      out.write("\t                                <label for=\"\" class=\"sr-only\">구매수량</label>\n");
      out.write("\t                                <button type=\"button\" class=\"btn-minus-");
      out.print(cart.getCartNo() );
      out.write("\"><span id=\"btn-minus\" class=\"glyphicon glyphicon-minus\" aria-hidden=\"true\"></span></button>\n");
      out.write("\t                                <input type=\"text\" name=\"orderNo\" id=\"orderNo\" class=\"text-center\" value=\"");
      out.print(cart.getItemQuantity() );
      out.write("\" disabled />\n");
      out.write("\t                                <button type=\"button\" class=\"btn-plus\"><span id=\"btn-plus\" class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span></button>\n");
      out.write("\t                            </div>\n");
      out.write(" \t                            <button type=\"button\" class=\"btn-radius btn-change\">변경</button>\n");
      out.write("\t                        </td>\n");
      out.write("\t                        <td>");
      out.print(rentPeriod);
      out.write("일</td>\n");
      out.write("\t                        <td class=\"dpEa\">");
      out.print(pEa);
      out.write("</td>\n");
      out.write("\t                        <input type=\"hidden\" name=\"cartNo\" class=\"hidden-cartNo\" value=\"");
      out.print(cart.getCartNo() );
      out.write("\"/>\n");
      out.write("\t                    </tr>\n");
      out.write("\t\t\t\t\t");

						} //end of for
					
      out.write("\n");
      out.write("\t                </tbody>\n");
      out.write("\t            </table>\n");
      out.write("\t        </section>\n");
      out.write("        \t<!-- 장바구니 선택옵션 -->\n");
      out.write("\t        <section class=\"itemChk-wrapper\">\n");
      out.write("\t            <h3 class=\"sr-only\">장바구니 선택옵션</h3>\n");
      out.write("\t            <p>선택상품을</p>\n");
      out.write("\t            <button type=\"button\" class=\"btn-radius btn-chkDel\">삭제하기</button>\n");
      out.write("\t            <div class=\"btnChkAll-wrapper pull-right\">\n");
      out.write("\t                <button type=\"button\" class=\"btn-radius btn-chkAll\" >전체선택</button>\n");
      out.write("\t                <button type=\"button\" class=\"btn-radius btn-chkAllDel\">전체삭제</button>\n");
      out.write("\t\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/member/memberCartDeleteAll\" id=\"delAllFrm\" method=\"post\">\n");
      out.write("\t                \t<input type=\"hidden\" name=\"memberId\" value=\"");
      out.print(memberId);
      out.write("\" class=\"input-cartNo\"/>\n");
      out.write("\t                </form>\n");
      out.write("\t            </div>\n");
      out.write("\t        </section>\n");
      out.write("\t        <!-- 장바구니 선택/전체상품 가격보기 -->\n");
      out.write("            <section id=\"cartPrice-wrapper\" class=\"row\">\n");
      out.write("                <h3 class=\"sr-only\">장바구니 선택/전체상품 가격보기</h3>\n");
      out.write("                <div class=\"col-md-3\">\n");
      out.write("                    <p>장바구니 상품 <span class=\"strong em-blue\">");
      out.print(cartList.size() );
      out.write("</span>개의</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-9\">\n");
      out.write("                    <ul class=\"list-unstyled list-inline row\">\n");
      out.write("                        <li class=\"col-md-4 text-center cartPrice-inner\">\n");
      out.write("                            <p>상품금액</p>\n");
      out.write("                            <p id=\"total-dpEa\" class=\"strong price\">0</p>\n");
      out.write("                            <span class=\"symbol\">+</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"col-md-4 text-center cartPrice-inner\">\n");
      out.write("                            <p>배송비</p>\n");
      out.write("                            <p id=\"total-shipPrice\" class=\"strong price\">0</p>\n");
      out.write("                            <span class=\"symbol\">=</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"col-md-4 text-center cartPrice-inner\">\n");
      out.write("                            <p>결제예상금액</p>\n");
      out.write("                            <p id=\"total-price\" class=\"strong em-pink price\">0</p>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                <!-- 주문하기 버튼 -->\n");
      out.write("                <div class=\"col-md-12 btnOrder-wrapper text-center\">\n");
      out.write("                    <button type=\"button\" id=\"btn-orderChk\" class=\"btn-radius\">선택주문</button>\n");
      out.write("                    <button type=\"button\" id=\"btn-orderAll\" class=\"btn-radius\">전체주문</button>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("        </div>\n");
      out.write("        ");

			} //end of if
			else{
        
      out.write("\n");
      out.write("        \t<div id=\"warning-wrapper\" class=\"col-md-10 content-wrapper text-center\">\n");
      out.write("\t\t\t\t<p><span class=\"glyphicon glyphicon-remove-circle\" aria-hidden=\"true\"></span>등록된 상품이 없습니다.</p> \n");
      out.write("\t\t\t</div>\n");
      out.write("        ");

			}
        
      out.write("\n");
      out.write("        <div class=\"col-md-1\"></div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\t<footer class=\"container-fluid\">\n");
      out.write("\t    <div class=\"line-style\"></div>\n");
      out.write("\t    <!-- first line -->\n");
      out.write("\t    <div id=\"footer-menu\" class=\"row\">\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>회사소개</header>\n");
      out.write("\t            <ul class=\"list-unstyled\">\n");
      out.write("\t                <li><a href=\"#\">이용약관</a></li>\n");
      out.write("\t                <li><a href=\"#\">정책안내</a></li>\n");
      out.write("\t            </ul>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>고객서비스</header>\n");
      out.write("\t            <ul class=\"list-unstyled\">\n");
      out.write("\t                <li><a href=\"#\">FAQ</a></li>\n");
      out.write("\t                <li><a href=\"#\">1:1문의</a></li>\n");
      out.write("\t                <li><a href=\"#\">주문현황</a></li>\n");
      out.write("\t            </ul>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>문의하기</header>\n");
      out.write("\t            <p id=\"q-call\" class=\"lead\">1577-1577</p>\n");
      out.write("\t            <p id=\"q-email\" class=\"lead\">reflex@naver.com</p>\n");
      out.write("\t            <p>평일 10:00~18:00</p>\n");
      out.write("\t            <p>주말 및 공휴일 휴무</p>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>SNS</header>\n");
      out.write("\t            <ul class=\"list-unstyled\">\n");
      out.write("\t                <li><a href=\"#\">Facebook</a></li>\n");
      out.write("\t                <li><a href=\"#\">Instagram</a></li>\n");
      out.write("\t                <li><a href=\"#\">Twitter</a></li>\n");
      out.write("\t            </ul>\n");
      out.write("\t        </div>\n");
      out.write("\t    </div>\n");
      out.write("\t    <!-- second line -->\n");
      out.write("\t    <div id=\"about\" class=\"row\">\n");
      out.write("\t        <p class=\"eng\">re:flex</p>\n");
      out.write("\t        <p>대표:유찬호<span class=\"bar\"></span>사업자등록번호:419-87-00807<span class=\"bar\"></span>통신판매업신고:제 2017-서울마포-2273호</p>\n");
      out.write("\t        <p>주소: 서울특별시 마포구 동교동 203-43 4층<span class=\"bar\"></span>대표전화:1566-6813<span class=\"bar\"></span>FAX:070-7848-0818<span class=\"bar\"></span>이메일:reflex@naver.com</p>\n");
      out.write("\t        <p>개인정보관리책임자:유찬호</p>\n");
      out.write("\t    </div>\n");
      out.write("\t    <div id=\"copyright\" class=\"line-style\"><span>ⓒ</span>2019 re:flex</div>\n");
      out.write("\t</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
